/*
Criação das procedures do Sispad
André - 17/09/2009
*/

CREATE PROCEDURE [dbo].[proc_SISPAD_ListaPresenca]
@IDEVENTO INT
AS
BEGIN
	DECLARE @INICIO DATETIME, @QTDDIAS INT, @CONTADOR INT
	CREATE TABLE #LISTAPRESENCA (PARTICIPANTE VARCHAR(120), DATA DATETIME)
	SELECT
	@INICIO = CAST(CONVERT(VARCHAR, DATAHORAINICIOEVENTO, 112) AS DATETIME)
	, @QTDDIAS = DATEDIFF(DAY, DATAHORAINICIOEVENTO, DATAHORAFIMEVENTO) + 1
	FROM EVENTOSSISPAD
	WHERE IDEVENTO = @IDEVENTO
	SET @CONTADOR = 0
	WHILE @CONTADOR < @QTDDIAS
	BEGIN	
		INSERT INTO #LISTAPRESENCA 
		SELECT DISTINCT 
		PS.NOME
		, DATEADD(DAY, @CONTADOR, @INICIO) 
		FROM EVENTOSSISPAD ES
		INNER JOIN SOLICITACOESVIAGEM SV ON SV.IDEVENTO = ES.IDEVENTO
		INNER JOIN PESSOASSOLICITACOESVIAGEM PSV ON PSV.IDSOLICITACAOVIAGEM = SV.IDSOLICITACAOVIAGEM
		INNER JOIN PESSOASSISPAD PSS ON PSS.IDPESSOASISPAD = PSV.IDPESSOAPASSAGEIRO
		INNER JOIN PESSOAS PS ON PS.IDPESSOA = PSS.IDPESSOA
		WHERE ES.IDEVENTO = @IDEVENTO
		ORDER BY PS.NOME
		
		SET @CONTADOR = @CONTADOR + 1
	END
	SELECT PARTICIPANTE, DATA FROM #LISTAPRESENCA
	DROP TABLE #LISTAPRESENCA
END
