

CREATE FUNCTION dbo.ufn_ValidarCpfCnpj (@CPF_CNPJ VARCHAR(20))
RETURNS BIT
AS 
BEGIN 
	DECLARE
		@I INT,
		@J INT,
		@N INT,
		@DIGITO1 INT,
		@DIGITO2 INT,
		@TOTAL_TMP INT,
		@COEFICIENTE_TMP INT,
		@DIGITO_TMP INT,
		@VALOR_TMP INT,
		@VALOR1 INT,
		@VALOR2 INT,
		@RESULTADO CHAR(1),
		@CPF_CNPJ_NUMERICO BIT 
    
          
	SET @RESULTADO = 0
	SET @CPF_CNPJ_NUMERICO = ISNUMERIC(@CPF_CNPJ)
     
    IF (@CPF_CNPJ_NUMERICO = 1) 
    BEGIN         
		SET @J = 1
		SET @N = LEN(@CPF_CNPJ)
		SET @DIGITO1 = SUBSTRING(@CPF_CNPJ, LEN(@CPF_CNPJ) - 1, 1)
		SET @DIGITO2 = SUBSTRING(@CPF_CNPJ, LEN(@CPF_CNPJ), 1)
		
		WHILE @J <= 2
		BEGIN
			SELECT
				@TOTAL_TMP = 0,
				@COEFICIENTE_TMP = 2,
				@I = @N + @J - 3

			WHILE @I >= 0
			BEGIN
				SELECT
					@DIGITO_TMP = SUBSTRING(@CPF_CNPJ, @I, 1),
					@TOTAL_TMP = @TOTAL_TMP + (@DIGITO_TMP * @COEFICIENTE_TMP),
					@COEFICIENTE_TMP = @COEFICIENTE_TMP + 1,
					@I = @I - 1 

				IF @COEFICIENTE_TMP > 9 AND @N = 14
					SET @COEFICIENTE_TMP = 2
			END

			SET @VALOR_TMP = 11 - (@TOTAL_TMP % 11)

			IF (@VALOR_TMP >= 10)
				SET @VALOR_TMP = 0

			IF @J = 1
				SET @VALOR1 = @VALOR_TMP
			ELSE
				SET @VALOR2 = @VALOR_TMP

			SET @J = @J + 1 
		END
		SET @RESULTADO = CASE WHEN @VALOR1 = @DIGITO1 AND @VALOR2 = @DIGITO2 THEN 1 ELSE 0 END
	END
	ELSE 
		SET @RESULTADO = 0
	RETURN @RESULTADO
END	
