CREATE TABLE [dbo].[ParametrosSisdoc] (
    [IdParametroSisdoc]              INT           IDENTITY (1, 1) NOT NULL,
    [NumeracaoAutoProtocolo]         BIT           NULL,
    [TamanhoNumeroProtocolo]         INT           NULL,
    [ReiniciaNumeracaoAnual]         BIT           NULL,
    [AceitaNumeracaoDuplicada]       BIT           NULL,
    [ProtocoloAutoIncDocsEntradas]   BIT           NULL,
    [ProtocoloAutoIncDocsSaidas]     BIT           NULL,
    [ProtocoloAutoIncDocsInternos]   BIT           NULL,
    [AnoPrefixo]                     BIT           NULL,
    [NumProtPorTipoDoc]              BIT           NULL,
    [TramitacoesEnviar]              INT           NULL,
    [TramitacoesReceber]             INT           NULL,
    [TramitacoesAlterar]             INT           NULL,
    [OcorrenciasAlterarExcluir]      INT           NULL,
    [FiltraResponsavelLocal]         BIT           NULL,
    [AlteraNivelDoc]                 BIT           CONSTRAINT [DF_ParametrosSisdoc_AlteraNivelDoc] DEFAULT ((0)) NULL,
    [TramitacoesAlterarExt]          INT           NULL,
    [SequencialNumProtocolo]         INT           NULL,
    [SequencialNumProtocoloAno]      INT           NULL,
    [AnoSequencialNumProtocolo]      INT           NULL,
    [TituloRelatorio]                VARCHAR (50)  NULL,
    [SubTituloRelatorio]             VARCHAR (50)  NULL,
    [Logotipo]                       IMAGE         NULL,
    [PermiteVersaoAnterior]          CHAR (1)      NULL,
    [TamAssunto]                     VARCHAR (4)   CONSTRAINT [DF__PARAMETRO__TamAs__41104BD3] DEFAULT ((100)) NULL,
    [UltimoInicioEtiqueta]           INT           NULL,
    [UltimoFimEtiqueta]              INT           NULL,
    [UtilizarUsuarioPadrao]          BIT           NULL,
    [AbreMSWordDocSaida]             CHAR (1)      CONSTRAINT [DF__Parametro__AbreM__4D398ABC] DEFAULT ('N') NULL,
    [FileNameLogoMSWord]             VARCHAR (250) NULL,
    [PastaSalvarMSWord]              VARCHAR (200) NULL,
    [AutoPesquisaDoc]                BIT           DEFAULT ((0)) NULL,
    [NivelAlteracaoDadosDocumentos]  INT           CONSTRAINT [DEF_ParametrosSisdoc_NivelAlteracaoDadosDocumentos] DEFAULT ((0)) NULL,
    [UtilizaControleDigitalizacoes]  BIT           CONSTRAINT [DF_ParametrosSisdoc_UtilizaControleDigitalizacoes] DEFAULT ((0)) NULL,
    [AlertarNumDocumentoDuplicado]   BIT           DEFAULT ((0)) NOT NULL,
    [AlertaDocVencido]               BIT           DEFAULT ((0)) NOT NULL,
    [UtilizaDataPrevisaoDoc]         BIT           DEFAULT ((0)) NOT NULL,
    [IgnorarZerosEsqNrDoc]           BIT           CONSTRAINT [DF_ParametrosSisdoc_IgnorarZerosEsqNrDoc] DEFAULT ((0)) NULL,
    [FiltrarTipoDocDepartamento]     BIT           NULL,
    [NumUnicaUtilizar]               BIT           CONSTRAINT [DEF_ParametrosSisdoc_NumUnicaUtilizar] DEFAULT ((0)) NOT NULL,
    [NumUnicaPrefixo]                VARCHAR (20)  NULL,
    [NumUnicaSufixo]                 VARCHAR (20)  NULL,
    [NumUnicaTamanho]                INT           NULL,
    [NumUnicaNumero]                 INT           NULL,
    [ServidorDigitalizacao]          VARCHAR (35)  NULL,
    [BaseDigitalizacao]              VARCHAR (35)  NULL,
    [UsuarioBaseDigitalizacao]       VARCHAR (35)  NULL,
    [SenhaBaseDigitalizacao]         VARCHAR (35)  NULL,
    [AutenticaWindows]               BIT           CONSTRAINT [DEF_Sisdoc_AutenticaWindows] DEFAULT ((0)) NOT NULL,
    [UtilizarGravarImagem]           BIT           CONSTRAINT [DEF_Sisdoc_UtilizarGravarImagem] DEFAULT ((0)) NOT NULL,
    [AdicionarPaginasProcessos]      BIT           CONSTRAINT [DEF_Sisdoc_AdicionarPaginasProcessos] DEFAULT ((0)) NOT NULL,
    [QtdDiasMaximoParaEditarArquivo] INT           NULL,
    [AvisaDiasAntesVencido]          INT           NULL,
    CONSTRAINT [PK_ParametrosSisdoc] PRIMARY KEY CLUSTERED ([IdParametroSisdoc] ASC)
);

