CREATE TABLE [dbo].[PessoasSolicitacoesViagem] (
    [IdPessoaSolicitacaoViagem] INT           IDENTITY (1, 1) NOT NULL,
    [IdSolicitacaoViagem]       INT           NOT NULL,
    [IdPessoaPassageiro]        INT           NOT NULL,
    [CodBanco]                  CHAR (3)      NULL,
    [CodAgencia]                VARCHAR (20)  NULL,
    [CodConta]                  VARCHAR (20)  NULL,
    [IdCentroCusto]             INT           NULL,
    [Diaria]                    BIT           NULL,
    [Indenizacao]               BIT           NULL,
    [IdTipoPessoa]              INT           NULL,
    [ReservaHotel]              BIT           NULL,
    [Acomodacao]                VARCHAR (150) NULL,
    [QtdReserva]                INT           NULL,
    [ObservacoesReserva]        TEXT          NULL,
    [IdSituacaoSolicitacao]     INT           NULL,
    [Taxi]                      BIT           NULL,
    [QtdTaxi]                   INT           NULL,
    [ValorDeducaoVRA]           MONEY         NULL,
    [DataPrestacaoConta]        DATETIME      NULL,
    [ValorReembolso]            MONEY         NULL,
    [ValorDevolucao]            MONEY         NULL,
    [ObservacaoPrestacaoConta]  TEXT          NULL,
    [FormatoSolicitacao]        INT           NULL,
    [NossoNumero]               NVARCHAR (25) NULL,
    [TipoConta]                 INT           CONSTRAINT [DF__PessoasSo__TipoC__2FA62C43] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_PessoasSolicitacoesViagem_1] PRIMARY KEY CLUSTERED ([IdPessoaSolicitacaoViagem] ASC),
    CONSTRAINT [FK_PessoasSolicitacoesViagem_CentroCustos] FOREIGN KEY ([IdCentroCusto]) REFERENCES [dbo].[CentroCustos] ([IdCentroCusto]),
    CONSTRAINT [FK_PessoasSolicitacoesViagem_PessoasSispad] FOREIGN KEY ([IdPessoaPassageiro]) REFERENCES [dbo].[PessoasSispad] ([IdPessoaSispad]),
    CONSTRAINT [FK_PessoasSolicitacoesViagem_SolicitacoesViagem] FOREIGN KEY ([IdSolicitacaoViagem]) REFERENCES [dbo].[SolicitacoesViagem] ([IdSolicitacaoViagem]),
    CONSTRAINT [FK_PessoasSolicitacoesViagem_TiposPessoa] FOREIGN KEY ([IdTipoPessoa]) REFERENCES [dbo].[TiposPessoa] ([IdTipoPessoa])
);

