CREATE TABLE [dbo].[PessoasJuridicas] (
    [IdPessoaJuridica]              INT            IDENTITY (1, 1) NOT NULL,
    [IdUnidadeConselho]             INT            NULL,
    [IdSubRegiao]                   INT            NULL,
    [IdNatureza]                    INT            NULL,
    [IdMatriz]                      INT            NULL,
    [IdTipoInscricao]               INT            NULL,
    [SituacaoAtual]                 VARCHAR (50)   NULL,
    [CategoriaAtual]                VARCHAR (40)   NULL,
    [CNPJ]                          VARCHAR (14)   NULL,
    [InscricaoEstadual]             VARCHAR (14)   NULL,
    [Nome]                          VARCHAR (100)  NULL,
    [NomeFantasia]                  VARCHAR (80)   NULL,
    [Codigo]                        VARCHAR (5)    NULL,
    [Sigla]                         VARCHAR (15)   NULL,
    [DataFundacao]                  DATETIME       NULL,
    [EMail]                         VARCHAR (250)  NULL,
    [Telefone]                      VARCHAR (100)  NULL,
    [Endereco]                      VARCHAR (60)   NULL,
    [NomeBairro]                    VARCHAR (35)   NULL,
    [NomeCidade]                    VARCHAR (30)   NULL,
    [SiglaUf]                       VARCHAR (2)    NULL,
    [CEP]                           VARCHAR (8)    NULL,
    [Atualizado]                    BIT            NULL,
    [DataUltimaAtualizacao]         DATETIME       NULL,
    [RegistroConselhoAtual]         VARCHAR (20)   NULL,
    [DataInscricao]                 DATETIME       NULL,
    [Observacoes]                   TEXT           NULL,
    [Processo]                      VARCHAR (15)   NULL,
    [CaixaPostal]                   VARCHAR (15)   NULL,
    [IndicativoPJ1]                 BIT            NULL,
    [IndicativoPJ2]                 BIT            NULL,
    [IndicativoPJ3]                 BIT            NULL,
    [AtualizacaoWeb]                VARCHAR (8000) NULL,
    [IdPesJuridOld]                 INT            NULL,
    [IDEntidadeOld]                 INT            NULL,
    [Atividades]                    TEXT           NULL,
    [DataInclusaoEmail]             DATETIME       NULL,
    [TelefoneCelular]               VARCHAR (100)  NULL,
    [TelefoneOutros]                VARCHAR (100)  NULL,
    [CodigoBarras]                  VARCHAR (16)   NULL,
    [IdFaixaCapital]                INT            NULL,
    [Site]                          VARCHAR (50)   NULL,
    [AlfaOutros1PJ]                 VARCHAR (80)   NULL,
    [idTabela1PJ]                   INT            NULL,
    [ExibirDadosWeb]                BIT            NULL,
    [AlfaOutros2PJ]                 VARCHAR (80)   NULL,
    [AlfaOutros3PJ]                 VARCHAR (80)   NULL,
    [IdDetalhePessoa1]              INT            NULL,
    [IdDetalhePessoa2]              INT            NULL,
    [IdDetalhePessoa3]              INT            NULL,
    [IdDetalhePessoa4]              INT            NULL,
    [IdDetalhePessoa5]              INT            NULL,
    [UsuarioUltimaAtualizacao]      VARCHAR (150)  NULL,
    [DepartamentoUltimaAtualizacao] VARCHAR (60)   NULL,
    [MalaDireta]                    BIT            NULL,
    [AgenciaDebitoConta]            VARCHAR (5)    NULL,
    [ContaDebitoConta]              VARCHAR (15)   NULL,
    [IdBancoDebitoConta]            INT            NULL,
    [NomeUsuario]                   VARCHAR (30)   NULL,
    [DepartamentoUsuario]           VARCHAR (60)   NULL,
    [DtUltimaAtualizacaoContato]    DATETIME       NULL,
    [UsuUltimaAtualizacaoContato]   VARCHAR (150)  NULL,
    [DepUltimaAtualizacaoContato]   VARCHAR (60)   NULL,
    [Data1PJ]                       DATETIME       NULL,
    [MotivoEnquadramento]           VARCHAR (4000) NULL,
    [IdPaisEndereco]                INT            NULL,
    [ComplementoEndereco]           TEXT           NULL,
    [Data2PJ]                       DATETIME       NULL,
    [Data3PJ]                       DATETIME       NULL,
    [Data4PJ]                       DATETIME       NULL,
    [IdRegiaoAdministrativa]        INT            NULL,
    [IdOrigemInscricao]             INT            NULL,
    [IdUsuarioCriacao]              INT            NULL,
    [IdDepartamentoCriacao]         INT            NULL,
    [IdDelegaciaCriacao]            INT            NULL,
    [NIRE]                          VARCHAR (20)   NULL,
    [DtConstitutiva]                DATETIME       NULL,
    [DtAltEndereco]                 DATETIME       NULL,
    [DtAltCapSocial]                DATETIME       NULL,
    [DtAltContratual]               DATETIME       NULL,
    [ProcessoSituacao]              INT            NULL,
    [ProcessoDataAbertura]          DATETIME       NULL,
    [ProcessoDataConclusao]         DATETIME       NULL,
    [NumeroSeguranca]               INT            NULL,
    [E_Filial]                      BIT            CONSTRAINT [DEF_PessoasJuridicas_E_Filial] DEFAULT ((0)) NOT NULL,
    [DissolucaoContratual]          BIT            CONSTRAINT [DEF_PessoasJuridicas_DissolucaoContratual] DEFAULT ((0)) NOT NULL,
    [RedesSociais]                  VARCHAR (1000) NULL,
    [DataPedidoInscricao]           DATETIME       NULL,
    [IdSoci]                        INT            NULL,
    [Livro]                         VARCHAR (10)   NULL,
    [Folha]                         VARCHAR (10)   NULL,
    [SiteDivulgacao]                BIT            NULL,
    [EMailDivulgacao]               BIT            NULL,
    [TelefoneDivulgacao]            BIT            NULL,
    [TelCelDivulgacao]              BIT            NULL,
    [TelOutDivulgacao]              BIT            NULL,
    [CalculaPorte]                  BIT            CONSTRAINT [DF_PessoasJuridicas_CalculaPorte] DEFAULT ((0)) NOT NULL,
    [QtdFunc]                       INT            NULL,
    [Potencia]                      INT            NULL,
    [Porte]                         VARCHAR (20)   CONSTRAINT [DF_PessoasJuridicas_Porte] DEFAULT ('Médio-Grande Porte') NOT NULL,
    CONSTRAINT [PK_PessoaJuridica] PRIMARY KEY NONCLUSTERED ([IdPessoaJuridica] ASC),
    CONSTRAINT [FK_PessoaJuridicaPais_Nacionalidades] FOREIGN KEY ([IdPaisEndereco]) REFERENCES [dbo].[Nacionalidades] ([IdNacionalidade]),
    CONSTRAINT [FK_PessoasJuridicas_BancosSiscafw] FOREIGN KEY ([IdBancoDebitoConta]) REFERENCES [dbo].[BancosSiscafw] ([IdBancoSiscafw]),
    CONSTRAINT [FK_PessoasJuridicas_Departamentos] FOREIGN KEY ([IdDepartamentoCriacao]) REFERENCES [dbo].[Departamentos] ([IdDepto]),
    CONSTRAINT [FK_PessoasJuridicas_DetalhesPessoas1] FOREIGN KEY ([IdDetalhePessoa1]) REFERENCES [dbo].[DetalhesPessoas1] ([IdDetalhePessoa1]),
    CONSTRAINT [FK_PessoasJuridicas_DetalhesPessoas2] FOREIGN KEY ([IdDetalhePessoa2]) REFERENCES [dbo].[DetalhesPessoas2] ([IdDetalhePessoa2]),
    CONSTRAINT [FK_PessoasJuridicas_DetalhesPessoas3] FOREIGN KEY ([IdDetalhePessoa3]) REFERENCES [dbo].[DetalhesPessoas3] ([IdDetalhePessoa3]),
    CONSTRAINT [FK_PessoasJuridicas_DetalhesPessoas4] FOREIGN KEY ([IdDetalhePessoa4]) REFERENCES [dbo].[DetalhesPessoas4] ([IdDetalhePessoa4]),
    CONSTRAINT [FK_PessoasJuridicas_DetalhesPessoas5] FOREIGN KEY ([IdDetalhePessoa5]) REFERENCES [dbo].[DetalhesPessoas5] ([IdDetalhePessoa5]),
    CONSTRAINT [FK_PessoasJuridicas_FaixasCapitalPJ] FOREIGN KEY ([IdFaixaCapital]) REFERENCES [dbo].[FaixasCapitalPJ] ([IdFaixaCapital]),
    CONSTRAINT [FK_PessoasJuridicas_Matriz] FOREIGN KEY ([IdMatriz]) REFERENCES [dbo].[PessoasJuridicas] ([IdPessoaJuridica]) NOT FOR REPLICATION,
    CONSTRAINT [FK_PessoasJuridicas_NaturezasPJ] FOREIGN KEY ([IdNatureza]) REFERENCES [dbo].[NaturezasPJ] ([IdNaturezaPJ]) NOT FOR REPLICATION,
    CONSTRAINT [FK_PessoasJuridicas_OrigensInscricao] FOREIGN KEY ([IdOrigemInscricao]) REFERENCES [dbo].[OrigensInscricao] ([IdOrigemInscricao]),
    CONSTRAINT [FK_PessoasJuridicas_Pessoas_SubRegiao] FOREIGN KEY ([IdSubRegiao]) REFERENCES [dbo].[Pessoas] ([IdPessoa]) NOT FOR REPLICATION,
    CONSTRAINT [FK_PessoasJuridicas_Pessoas_UnidadeConselho] FOREIGN KEY ([IdUnidadeConselho]) REFERENCES [dbo].[Pessoas] ([IdPessoa]) NOT FOR REPLICATION,
    CONSTRAINT [FK_PessoasJuridicas_PessoasDelegacia] FOREIGN KEY ([IdDelegaciaCriacao]) REFERENCES [dbo].[Pessoas] ([IdPessoa]),
    CONSTRAINT [FK_PessoasJuridicas_PessoasJuridicasTabela1] FOREIGN KEY ([idTabela1PJ]) REFERENCES [dbo].[PessoasJuridicasTabela1] ([idTabela1PJ]),
    CONSTRAINT [FK_PessoasJuridicas_RegioesAdministrativas] FOREIGN KEY ([IdRegiaoAdministrativa]) REFERENCES [dbo].[RegioesAdministrativas] ([IdRegiaoAdministrativa]),
    CONSTRAINT [FK_PessoasJuridicas_TiposInscricao] FOREIGN KEY ([IdTipoInscricao]) REFERENCES [dbo].[TiposInscricao] ([IdTipoInscricao]) NOT FOR REPLICATION,
    CONSTRAINT [FK_PessoasJuridicas_Usuarios] FOREIGN KEY ([IdUsuarioCriacao]) REFERENCES [dbo].[Usuarios] ([IdUsuario])
);


GO
CREATE TRIGGER [dbo].[Trg_PessoasJuridicas_Usuario] on [dbo].[PessoasJuridicas] for insert
	  as
      declare @IdPessoaJuridica integer
      declare @Depto    varchar(60) 
      select @IdPessoaJuridica = IdPessoaJuridica from inserted   
      if (@IdPessoaJuridica > 0)
	     begin
            select @Depto = NomeDepto from Departamentos inner join Usuarios on
			Departamentos.IdDepto = Usuarios.IdDepartamento where NomeUsuario = host_name()		   				     			
		  update PessoasJuridicas set NomeUsuario = host_name(),DepartamentoUsuario = @Depto
    	  where IdPessoaJuridica = @IdPessoaJuridica
         end 





