CREATE TABLE [dbo].[Pessoas] (
    [IdPessoa]                    INT            IDENTITY (1, 1) NOT NULL,
    [IdPessoaPrincipal]           INT            NULL,
    [IdContaProvisao]             INT            NULL,
    [IdFormaCredito]              INT            NULL,
    [Nome]                        VARCHAR (120)  NOT NULL,
    [CNPJCPF]                     VARCHAR (14)   NULL,
    [NomeFantasia]                VARCHAR (50)   NULL,
    [Endereco]                    VARCHAR (130)  NULL,
    [NomeBairro]                  VARCHAR (40)   NULL,
    [NomeCidade]                  VARCHAR (40)   NULL,
    [SiglaUF]                     VARCHAR (2)    NULL,
    [CEP]                         VARCHAR (8)    NULL,
    [DataUltimaAtualizacaoEnd]    DATETIME       NULL,
    [Telefone]                    VARCHAR (50)   NULL,
    [Email]                       VARCHAR (60)   NULL,
    [Banco]                       VARCHAR (20)   NULL,
    [Agencia]                     VARCHAR (20)   NULL,
    [Conta]                       VARCHAR (20)   NULL,
    [UsaBanco]                    BIT            CONSTRAINT [DF_PessoasUsaBanco] DEFAULT ((1)) NOT NULL,
    [Habilitado]                  BIT            CONSTRAINT [DF_PessoasHabilitado] DEFAULT ((0)) NOT NULL,
    [Ativo]                       BIT            CONSTRAINT [DF_PessoasAtivo] DEFAULT ((0)) NOT NULL,
    [Atualizado]                  BIT            CONSTRAINT [DF_PessoasAtualizado] DEFAULT ((1)) NOT NULL,
    [E_ConselhoProfissao]         BIT            NULL,
    [InscricaoEstadual]           VARCHAR (20)   NULL,
    [InscricaoMunicipal]          VARCHAR (20)   NULL,
    [DataRegistro]                DATETIME       NULL,
    [DataFundacao]                DATETIME       NULL,
    [TipoConselho]                INT            NULL,
    [NaturezaJuridica]            VARCHAR (25)   NULL,
    [CapitalSocial]               MONEY          NULL,
    [Codigo]                      VARCHAR (5)    NULL,
    [Sigla]                       VARCHAR (15)   NULL,
    [ObjetoSocial]                TEXT           NULL,
    [Observacoes]                 TEXT           NULL,
    [E_PessoaJuridica]            BIT            NULL,
    [E_Fiscal]                    BIT            NULL,
    [Assina]                      BIT            NULL,
    [TipoConta]                   INT            NULL,
    [E_InstituicaoEnsino]         BIT            CONSTRAINT [DF__Pessoas__E_Insti__5BAF3376] DEFAULT ((0)) NULL,
    [IdPessoaOld]                 INT            NULL,
    [IdNatureza]                  INT            NULL,
    [IdProfissional]              INT            NULL,
    [IdPessoaJuridica]            INT            NULL,
    [IdMunicipio]                 INT            NULL,
    [Site]                        VARCHAR (250)  NULL,
    [IdDetalhePessoa1]            INT            NULL,
    [IdDetalhePessoa2]            INT            NULL,
    [IdDetalhePessoa3]            INT            NULL,
    [IdDetalhePessoa4]            INT            NULL,
    [IdDetalhePessoa5]            INT            NULL,
    [UsuarioUltimaAtualizacaoEnd] VARCHAR (35)   NULL,
    [DeptoUltimaAtualizacaoEnd]   VARCHAR (60)   NULL,
    [PromoveCursosEventos]        BIT            NULL,
    [PIS]                         VARCHAR (15)   NULL,
    [INSS]                        VARCHAR (15)   NULL,
    [CodFaculdade]                INT            NULL,
    [IdBancoDebitoConta]          INT            NULL,
    [CaixaPostal]                 VARCHAR (15)   NULL,
    [NumeroProcessoPessoas]       VARCHAR (10)   NULL,
    [Contato]                     VARCHAR (120)  NULL,
    [ModuloSispad]                INT            NULL,
    [VisivelSG_SIPRO]             BIT            CONSTRAINT [DF__Pessoas__Visivel__4E2DAEF5] DEFAULT ((0)) NULL,
    [DataAtualizacao]             DATETIME       NULL,
    [DataAlteracao]               DATETIME       NULL,
    [AssinaDocumentoPagamento]    BIT            NULL,
    [NomeAbreviadoCarteiraEst]    VARCHAR (120)  NULL,
    [EleicaoNumeroZona]           INT            NULL,
    [EleicaoQtdeUrnas]            INT            NULL,
    [EleicaoNumeroSecaoInicial]   INT            NULL,
    [EleicaoCodigoMunicipio]      INT            NULL,
    [OperacaoConta]               VARCHAR (3)    NULL,
    [IdPessoaJuridicaMatriz]      INT            NULL,
    [DataInativo]                 DATETIME       NULL,
    [DataAniversario]             DATETIME       NULL,
    [Sexo]                        VARCHAR (1)    NULL,
    [RG]                          NVARCHAR (14)  NULL,
    [OrgaoExpedidor]              NVARCHAR (15)  NULL,
    [Titulos]                     NVARCHAR (60)  NULL,
    [InstituicaoEnsino]           NVARCHAR (100) NULL,
    [Graduacao]                   NVARCHAR (30)  NULL,
    [RegNacional]                 NVARCHAR (20)  NULL,
    [NumRegistro]                 NVARCHAR (20)  NULL,
    [IdTipoEntidade]              INT            NULL,
    [Email2]                      VARCHAR (60)   NULL,
    [TelefoneTrabalho]            VARCHAR (50)   NULL,
    [Celular]                     VARCHAR (50)   NULL,
    [RecadoFax]                   VARCHAR (50)   NULL,
    [Complemento]                 VARCHAR (50)   NULL,
    [ECEndereco]                  VARCHAR (60)   NULL,
    [ECComplemento]               VARCHAR (50)   NULL,
    [ECBairro]                    VARCHAR (40)   NULL,
    [ECCidade]                    VARCHAR (40)   NULL,
    [ECUF]                        VARCHAR (2)    NULL,
    [ECCEP]                       VARCHAR (8)    NULL,
    [RGDataEmissao]               DATETIME       NULL,
    [RGOrgaoExpediror]            VARCHAR (20)   NULL,
    [RGUf]                        VARCHAR (2)    NULL,
    [RNE]                         VARCHAR (20)   NULL,
    [Naturalidade]                VARCHAR (50)   NULL,
    [NaturalidadeUF]              VARCHAR (2)    NULL,
    [Nacionalidade]               VARCHAR (50)   NULL,
    [NomePai]                     VARCHAR (50)   NULL,
    [NomeMae]                     VARCHAR (50)   NULL,
    [EstadoCivil]                 VARCHAR (30)   NULL,
    [TENumero]                    VARCHAR (20)   NULL,
    [TEZona]                      VARCHAR (20)   NULL,
    [TESessao]                    VARCHAR (20)   NULL,
    [TEDataEmissao]               DATETIME       NULL,
    [CarteiraReservista]          VARCHAR (20)   NULL,
    [CarteiraReservistaEmissao]   DATETIME       NULL,
    [CSM]                         VARCHAR (20)   NULL,
    [Universidade]                VARCHAR (60)   NULL,
    [CursoHabilitacao]            VARCHAR (60)   NULL,
    [DataColacao]                 DATETIME       NULL,
    [DocumentoApresentado]        VARCHAR (50)   NULL,
    [TipoInscricao]               VARCHAR (50)   NULL,
    [MotivoInscricao]             VARCHAR (50)   NULL,
    [SenhaPreCadastro]            VARCHAR (50)   NULL,
    [CategoriaDataInicio]         DATETIME       NULL,
    [IdCategoria]                 INT            NULL,
    [IdTipoInscricao]             INT            NULL,
    [IdMotivoInscricao]           INT            NULL,
    [IndCriacaoWeb]               BIT            CONSTRAINT [DF_PessoasIndCriacaoWeb] DEFAULT ((0)) NULL,
    [NIRE]                        VARCHAR (20)   NULL,
    [DtConstitutiva]              DATETIME       NULL,
    [DtAltEndereco]               DATETIME       NULL,
    [DtAltCapSocial]              DATETIME       NULL,
    [DtAltContratual]             DATETIME       NULL,
    [CSMEmissao]                  VARCHAR (4000) NULL,
    [DataAdmissao]                DATETIME       NULL,
    [EntidadeRegistro]            BIT            CONSTRAINT [DF_EntidadeRegistro] DEFAULT ((0)) NOT NULL,
    [UsuarioAlteracao]            VARCHAR (30)   NULL,
    [Inapto]                      BIT            CONSTRAINT [DEF_PessoasInapto] DEFAULT ((0)) NOT NULL,
    [DtSituacaoInstEnsino]        DATETIME       NULL,
    [DtCriacaoInstEnsino]         DATETIME       NULL,
    [DtCadastro]                  DATETIME       NULL,
    [SituacaoInstEnsino]          INT            NULL,
    [IdPaisEndereco]              INT            NULL,
    CONSTRAINT [PK_Pessoas] PRIMARY KEY NONCLUSTERED ([IdPessoa] ASC),
    CONSTRAINT [FK_Pessoas_BancosSiscafw] FOREIGN KEY ([IdBancoDebitoConta]) REFERENCES [dbo].[BancosSiscafw] ([IdBancoSiscafw]),
    CONSTRAINT [FK_Pessoas_DetalhesPessoas1] FOREIGN KEY ([IdDetalhePessoa1]) REFERENCES [dbo].[DetalhesPessoas1] ([IdDetalhePessoa1]),
    CONSTRAINT [FK_Pessoas_DetalhesPessoas2] FOREIGN KEY ([IdDetalhePessoa2]) REFERENCES [dbo].[DetalhesPessoas2] ([IdDetalhePessoa2]),
    CONSTRAINT [FK_Pessoas_DetalhesPessoas3] FOREIGN KEY ([IdDetalhePessoa3]) REFERENCES [dbo].[DetalhesPessoas3] ([IdDetalhePessoa3]),
    CONSTRAINT [FK_Pessoas_DetalhesPessoas4] FOREIGN KEY ([IdDetalhePessoa4]) REFERENCES [dbo].[DetalhesPessoas4] ([IdDetalhePessoa4]),
    CONSTRAINT [FK_Pessoas_DetalhesPessoas5] FOREIGN KEY ([IdDetalhePessoa5]) REFERENCES [dbo].[DetalhesPessoas5] ([IdDetalhePessoa5]),
    CONSTRAINT [FK_Pessoas_EstadosMunicipiosDES] FOREIGN KEY ([IdMunicipio]) REFERENCES [dbo].[EstadosMunicipiosDES] ([IdEstadoMunicipio]),
    CONSTRAINT [FK_Pessoas_FormasCredito] FOREIGN KEY ([IdFormaCredito]) REFERENCES [dbo].[FormasCredito] ([IdFormaCredito]) NOT FOR REPLICATION,
    CONSTRAINT [FK_Pessoas_Pessoas] FOREIGN KEY ([IdPessoaPrincipal]) REFERENCES [dbo].[Pessoas] ([IdPessoa]) NOT FOR REPLICATION,
    CONSTRAINT [FK_Pessoas_PlanoContas] FOREIGN KEY ([IdContaProvisao]) REFERENCES [dbo].[PlanoContas] ([IdConta]) NOT FOR REPLICATION,
    CONSTRAINT [FK_PessoasNaturezaPJ] FOREIGN KEY ([IdNatureza]) REFERENCES [dbo].[NaturezasPJ] ([IdNaturezaPJ]) NOT FOR REPLICATION
);

