CREATE TABLE [dbo].[Processos] (
    [IdProcesso]            INT           IDENTITY (1, 1) NOT NULL,
    [NumeroProcesso]        VARCHAR (20)  NULL,
    [Data1Proc]             DATETIME      NULL,
    [Data2Proc]             DATETIME      NULL,
    [Data3Proc]             DATETIME      NULL,
    [Data4Proc]             DATETIME      NULL,
    [Num1Proc]              INT           NULL,
    [Num2Proc]              INT           NULL,
    [Num3Proc]              INT           NULL,
    [Num4Proc]              INT           NULL,
    [Num5Proc]              INT           NULL,
    [IdTabela1Proc]         INT           NULL,
    [IdTabela2Proc]         INT           NULL,
    [IdTabela3Proc]         INT           NULL,
    [IdTabela4Proc]         INT           NULL,
    [IdTabela5Proc]         INT           NULL,
    [Alfa1Proc]             VARCHAR (300) NULL,
    [Alfa2Proc]             VARCHAR (300) NULL,
    [Alfa3Proc]             VARCHAR (300) NULL,
    [Alfa4Proc]             VARCHAR (300) NULL,
    [Alfa5Proc]             VARCHAR (300) NULL,
    [Valor1Proc]            MONEY         NULL,
    [Valor2Proc]            MONEY         NULL,
    [Valor3Proc]            MONEY         NULL,
    [IdCidade1]             INT           NULL,
    [IdCidade2]             INT           NULL,
    [IdUF1]                 INT           NULL,
    [IdUF2]                 INT           NULL,
    [Observacao]            TEXT          NULL,
    [IdTabela1Prof]         INT           NULL,
    [IdTabela1PJ]           INT           NULL,
    [IdTabela1Pessoa]       INT           NULL,
    [IdTabela2Prof]         INT           NULL,
    [IdTabela2PJ]           INT           NULL,
    [IdTabela2Pessoa]       INT           NULL,
    [IdTabela3Prof]         INT           NULL,
    [IdTabela3PJ]           INT           NULL,
    [IdTabela3Pessoa]       INT           NULL,
    [IdTabela4Prof]         INT           NULL,
    [IdTabela4PJ]           INT           NULL,
    [IdTabela4Pessoa]       INT           NULL,
    [Chk1]                  BIT           NULL,
    [Chk2]                  BIT           NULL,
    [Chk3]                  BIT           NULL,
    [IdTabela5Prof]         INT           NULL,
    [IdTabela5PJ]           INT           NULL,
    [IdTabela5Pessoa]       INT           NULL,
    [IdProcessoPrincipal]   INT           NULL,
    [NumeroProc]            BIGINT        NULL,
    [AnoProc]               INT           NULL,
    [NumProt]               INT           NULL,
    [IDTIPOPROCESSO]        INT           NULL,
    [IdEtapa]               INT           NULL,
    [Data5Proc]             DATETIME      NULL,
    [IdSecao]               INT           NULL,
    [IdTurma]               INT           NULL,
    [IdDepartamentoCriacao] INT           NULL,
    [IdUsuarioCriacao]      INT           NULL,
    [DataSolucao]           DATETIME      NULL,
    [DataAutuacao]          DATETIME      NULL,
    [DataCadastro]          DATETIME      NULL,
    [Volumes]               INT           NULL,
    [Prescricao]            DATETIME      NULL,
    [NumProcExterno]        VARCHAR (40)  NULL,
    [Alfa6Proc]             VARCHAR (300) NULL,
    [Alfa7Proc]             VARCHAR (300) NULL,
    [Alfa8Proc]             VARCHAR (300) NULL,
    [Alfa9Proc]             VARCHAR (300) NULL,
    [Alfa10Proc]            VARCHAR (300) NULL,
    [NumeroPasta]           INT           NULL,
    [ProcessoSituacao]      INT           NULL,
    [ProcessoDataAbertura]  DATETIME      NULL,
    [ProcessoDataConclusao] DATETIME      NULL,
    [EModeloDA]             BIT           CONSTRAINT [DF_Processos_EModeloDA] DEFAULT ((0)) NOT NULL,
    [IdCidade]              INT           NULL,
    CONSTRAINT [PK_Processo] PRIMARY KEY CLUSTERED ([IdProcesso] ASC),
    FOREIGN KEY ([IdEtapa]) REFERENCES [dbo].[Etapas] ([IdEtapa]),
    FOREIGN KEY ([IdSecao]) REFERENCES [dbo].[Secao] ([IdSecao]) NOT FOR REPLICATION,
    FOREIGN KEY ([IdTurma]) REFERENCES [dbo].[Turmas] ([IdTurma]) NOT FOR REPLICATION,
    CONSTRAINT [FK_Processos_Cidades] FOREIGN KEY ([IdCidade1]) REFERENCES [dbo].[Cidades] ([IdCidade]),
    CONSTRAINT [FK_Processos_Cidades1] FOREIGN KEY ([IdCidade2]) REFERENCES [dbo].[Cidades] ([IdCidade]),
    CONSTRAINT [FK_Processos_CidadesSubSecao] FOREIGN KEY ([IdCidade]) REFERENCES [dbo].[Cidades] ([IdCidade]),
    CONSTRAINT [FK_Processos_Estados] FOREIGN KEY ([IdUF1]) REFERENCES [dbo].[Estados] ([IdEstado]) NOT FOR REPLICATION,
    CONSTRAINT [FK_Processos_Estados1] FOREIGN KEY ([IdUF2]) REFERENCES [dbo].[Estados] ([IdEstado]) NOT FOR REPLICATION,
    CONSTRAINT [FK_Processos_Pessoas] FOREIGN KEY ([IdTabela1Pessoa]) REFERENCES [dbo].[Pessoas] ([IdPessoa]),
    CONSTRAINT [FK_Processos_Pessoas2] FOREIGN KEY ([IdTabela2Pessoa]) REFERENCES [dbo].[Pessoas] ([IdPessoa]),
    CONSTRAINT [FK_Processos_Pessoas3] FOREIGN KEY ([IdTabela3Pessoa]) REFERENCES [dbo].[Pessoas] ([IdPessoa]),
    CONSTRAINT [FK_Processos_Pessoas4] FOREIGN KEY ([IdTabela4Pessoa]) REFERENCES [dbo].[Pessoas] ([IdPessoa]),
    CONSTRAINT [FK_Processos_Pessoas5] FOREIGN KEY ([IdTabela5Pessoa]) REFERENCES [dbo].[Pessoas] ([IdPessoa]),
    CONSTRAINT [FK_Processos_PessoasJuridicas] FOREIGN KEY ([IdTabela1PJ]) REFERENCES [dbo].[PessoasJuridicas] ([IdPessoaJuridica]),
    CONSTRAINT [FK_Processos_PessoasJuridicas2] FOREIGN KEY ([IdTabela2PJ]) REFERENCES [dbo].[PessoasJuridicas] ([IdPessoaJuridica]),
    CONSTRAINT [FK_Processos_PessoasJuridicas3] FOREIGN KEY ([IdTabela3PJ]) REFERENCES [dbo].[PessoasJuridicas] ([IdPessoaJuridica]),
    CONSTRAINT [FK_Processos_PessoasJuridicas4] FOREIGN KEY ([IdTabela4PJ]) REFERENCES [dbo].[PessoasJuridicas] ([IdPessoaJuridica]),
    CONSTRAINT [FK_Processos_PessoasJuridicas5] FOREIGN KEY ([IdTabela5PJ]) REFERENCES [dbo].[PessoasJuridicas] ([IdPessoaJuridica]),
    CONSTRAINT [FK_Processos_Processos] FOREIGN KEY ([IdProcessoPrincipal]) REFERENCES [dbo].[Processos] ([IdProcesso]) NOT FOR REPLICATION,
    CONSTRAINT [FK_Processos_Processos1Tabela1] FOREIGN KEY ([IdTabela1Proc]) REFERENCES [dbo].[ProcessosTabela1] ([IdTabela1Proc]),
    CONSTRAINT [FK_Processos_Processos1Tabela2] FOREIGN KEY ([IdTabela2Proc]) REFERENCES [dbo].[ProcessosTabela2] ([IdTabela2Proc]),
    CONSTRAINT [FK_Processos_Processos1Tabela3] FOREIGN KEY ([IdTabela3Proc]) REFERENCES [dbo].[ProcessosTabela3] ([IdTabela3Proc]),
    CONSTRAINT [FK_Processos_Processos1Tabela4] FOREIGN KEY ([IdTabela4Proc]) REFERENCES [dbo].[ProcessosTabela4] ([IdTabela4Proc]),
    CONSTRAINT [FK_Processos_Processos1Tabela5] FOREIGN KEY ([IdTabela5Proc]) REFERENCES [dbo].[ProcessosTabela5] ([IdTabela5Proc]),
    CONSTRAINT [FK_Processos_ProcessosDepartamentos] FOREIGN KEY ([IdDepartamentoCriacao]) REFERENCES [dbo].[Departamentos] ([IdDepto]),
    CONSTRAINT [FK_Processos_ProcessosUsuarios] FOREIGN KEY ([IdUsuarioCriacao]) REFERENCES [dbo].[Usuarios] ([IdUsuario]),
    CONSTRAINT [FK_Processos_Prof] FOREIGN KEY ([IdTabela1Prof]) REFERENCES [dbo].[Profissionais] ([IdProfissional]),
    CONSTRAINT [FK_Processos_Prof2] FOREIGN KEY ([IdTabela2Prof]) REFERENCES [dbo].[Profissionais] ([IdProfissional]),
    CONSTRAINT [FK_Processos_Prof3] FOREIGN KEY ([IdTabela3Prof]) REFERENCES [dbo].[Profissionais] ([IdProfissional]),
    CONSTRAINT [FK_Processos_Prof4] FOREIGN KEY ([IdTabela4Prof]) REFERENCES [dbo].[Profissionais] ([IdProfissional]),
    CONSTRAINT [FK_Processos_Prof5] FOREIGN KEY ([IdTabela5Prof]) REFERENCES [dbo].[Profissionais] ([IdProfissional]),
    CONSTRAINT [FK_Processos_TipoProcesso] FOREIGN KEY ([IDTIPOPROCESSO]) REFERENCES [dbo].[TipoProcesso] ([IdTipoProcesso])
);

