CREATE TABLE [dbo].[ProfissionaisCarteira] (
    [IdHistoricoCarteira]             INT           IDENTITY (1, 1) NOT NULL,
    [IdProfissional]                  INT           NOT NULL,
    [NumeroCarteira]                  VARCHAR (20)  NULL,
    [DataExpedicao]                   DATETIME      NULL,
    [DataValidade]                    DATETIME      NULL,
    [IdSolicitacaoCarteira]           INT           NULL,
    [DataRecebimento]                 DATETIME      NULL,
    [DataEntrega]                     DATETIME      NULL,
    [Tipo]                            CHAR (1)      NULL,
    [EntreguePara]                    INT           NULL,
    [IdSubregiao]                     INT           NULL,
    [NotaFiscal]                      VARCHAR (20)  NULL,
    [NumeroSeguranca]                 VARCHAR (8)   NULL,
    [TipoRetorno]                     CHAR (1)      NULL,
    [SituacaoCedula]                  TINYINT       NULL,
    [MotivoPedido]                    VARCHAR (255) NULL,
    [MensagemCarteira]                VARCHAR (255) NULL,
    [MensagemUsuarioAtualizacao]      VARCHAR (30)  NULL,
    [MensagemDepartamentoAtualizacao] VARCHAR (60)  NULL,
    [MensagemDataAtualizacao]         DATETIME      NULL,
    [UsuarioUltimaAtualizacao]        VARCHAR (35)  NULL,
    [DepartamentoUltimaAtualizacao]   VARCHAR (60)  NULL,
    [DataUltimaAtualizacao]           DATETIME      NULL,
    [Via]                             TINYINT       NULL,
    [Reimpressao]                     BIT           CONSTRAINT [DF__Profissio__Reimp__12D7DEFD] DEFAULT ((0)) NULL,
    [Observacao]                      TEXT          NULL,
    [UsuarioImpressao]                VARCHAR (30)  NULL,
    CONSTRAINT [PK_ProfissionaisCarteira] PRIMARY KEY CLUSTERED ([IdHistoricoCarteira] ASC),
    CONSTRAINT [FK_ProfissionaisCarteira_Pessoas] FOREIGN KEY ([IdSubregiao]) REFERENCES [dbo].[Pessoas] ([IdPessoa]),
    CONSTRAINT [FK_ProfissionaisCarteira_Profissionais] FOREIGN KEY ([IdProfissional]) REFERENCES [dbo].[Profissionais] ([IdProfissional]),
    CONSTRAINT [FK_ProfissionaisCarteira_SolicitacoesCarteira] FOREIGN KEY ([IdSolicitacaoCarteira]) REFERENCES [dbo].[SolicitacaoCarteira] ([IdSolicitacaoCarteira])
);

