CREATE TABLE [dbo].[Relatorios] (
    [IdRelatorio]                INT           IDENTITY (1, 1) NOT NULL,
    [IdUsuario]                  INT           NULL,
    [IdSistema]                  INT           NULL,
    [Dominio]                    INT           NULL,
    [Selecao]                    TEXT          NULL,
    [Colunas]                    VARCHAR (254) NULL,
    [OrdemColunas]               VARCHAR (100) NULL,
    [OrdemResultado]             VARCHAR (100) NULL,
    [Agrupar]                    VARCHAR (100) NULL,
    [TituloResumido]             VARCHAR (120) NULL,
    [Titulo]                     VARCHAR (120) NULL,
    [Numerar]                    BIT           NULL,
    [IncluiMenu]                 BIT           NULL,
    [TotalItens]                 BIT           NULL,
    [TotalValor]                 BIT           NULL,
    [Retrato]                    BIT           NULL,
    [ForcaPagina]                BIT           NULL,
    [Zebrado]                    BIT           NULL,
    [NaoBaixado]                 BIT           NULL,
    [Baixado]                    BIT           NULL,
    [DataGeracao]                DATETIME      NULL,
    [IdConfigGeracaoDebito]      INT           NULL,
    [IdModeloDocumento]          INT           NULL,
    [TipoPessoa]                 INT           NULL,
    [UsoExclusivo]               BIT           NULL,
    [ExibirCliente]              BIT           NULL,
    [ExibirData]                 BIT           NULL,
    [ExibirVersao]               BIT           NULL,
    [Separador]                  BIT           NULL,
    [SubTitulo]                  VARCHAR (250) NULL,
    [MargemSuperior]             FLOAT (53)    NULL,
    [MargemInferior]             FLOAT (53)    NULL,
    [MargemEsquerda]             FLOAT (53)    NULL,
    [MargemDireita]              FLOAT (53)    NULL,
    [FonteSubTitulo]             VARCHAR (200) NULL,
    [FonteTitulo]                VARCHAR (200) NULL,
    [TituloSoma]                 VARCHAR (50)  NULL,
    [TituloSomaGeral]            VARCHAR (50)  NULL,
    [TituloTotalizadorGeral]     VARCHAR (50)  NULL,
    [TituloTotalLinhas]          VARCHAR (50)  NULL,
    [TituloTotalLinhasGrupo]     VARCHAR (50)  NULL,
    [TotalizaQuantidadeGeral]    BIT           NULL,
    [TotalizaQuantidadeGrupo]    BIT           NULL,
    [FonteCabecalho]             VARCHAR (200) NULL,
    [CorFundoCabecalho]          VARCHAR (200) NULL,
    [FonteCabecalhoSubGrupo]     VARCHAR (200) NULL,
    [CorFundoSubGrupo]           VARCHAR (200) NULL,
    [FonteTituloTotalizador]     VARCHAR (200) NULL,
    [FonteDetalhe]               VARCHAR (200) NULL,
    [FonteCliente]               VARCHAR (200) NULL,
    [FonteData]                  VARCHAR (200) NULL,
    [FonteNumFolha]              VARCHAR (200) NULL,
    [FonteVersaoSistema]         VARCHAR (200) NULL,
    [Acesso]                     VARCHAR (15)  NULL,
    [SomaSubGrupo]               VARCHAR (50)  NULL,
    [TituloSubGrupo]             VARCHAR (50)  NULL,
    [FonteRodape]                VARCHAR (200) NULL,
    [CorFundoRodape]             VARCHAR (200) NULL,
    [FonteSubGrupoRodape]        VARCHAR (200) NULL,
    [CorFundoSubGrupoRodape]     VARCHAR (200) NULL,
    [FonteSumario]               VARCHAR (200) NULL,
    [CorSumario]                 VARCHAR (200) NULL,
    [SUBSELECT]                  TEXT          NULL,
    [subSelectCa]                TEXT          NULL,
    [OpcoesSelecionadas]         TEXT          NULL,
    [EmDiaDevedoresDataRef]      DATETIME      NULL,
    [ListaConjunto]              TEXT          NULL,
    [RetiraParcelaCotaUnica]     BIT           CONSTRAINT [DF__Relatorio__Retir__4ED6BD4A] DEFAULT ((0)) NULL,
    [OrdemDecrescente]           BIT           CONSTRAINT [DF__Relatorio__Ordem__22F50DB0] DEFAULT ((0)) NULL,
    [OmitirNome]                 BIT           CONSTRAINT [DF__Relatorio__Omiti__42B89D23] DEFAULT ((0)) NULL,
    [ExibirCriterios]            BIT           CONSTRAINT [DF__Relatorio__Exibi__43ACC15C] DEFAULT ((0)) NULL,
    [TotalAquisicao]             BIT           CONSTRAINT [DF__Relatorio__Total__4B38D48B] DEFAULT ((0)) NULL,
    [TotalBaixa]                 BIT           CONSTRAINT [DF__Relatorio__Total__4C2CF8C4] DEFAULT ((0)) NULL,
    [EmDiaDevedoresPagEmAtraso]  BIT           NULL,
    [EmDiaDevedoresPagoNaoPago]  BIT           NULL,
    [QueDevamAnoPagEmAtraso]     BIT           NULL,
    [QueDevamAnoDatAnoRef]       INT           NULL,
    [SomarCampoMonetario]        BIT           NULL,
    [TituloQtdGrupo]             VARCHAR (50)  NULL,
    [ManterParcelasSemCotaUnica] BIT           NULL,
    [CondicaoPorQuantidade]      BIT           NULL,
    [OpLimitadorQuantidade]      INT           NULL,
    [NumLimitadorQuantidade]     INT           NULL,
    [EstruturaRelatorio]         TEXT          NULL,
    CONSTRAINT [PK_Relatorios] PRIMARY KEY NONCLUSTERED ([IdRelatorio] ASC),
    CONSTRAINT [FK_Relatorios_ConfigGeracaoDebito] FOREIGN KEY ([IdConfigGeracaoDebito]) REFERENCES [dbo].[ConfigGeracaoDebito] ([IdConfigGeracaoDebito]),
    CONSTRAINT [FK_Relatorios_ModelosDocumento] FOREIGN KEY ([IdModeloDocumento]) REFERENCES [dbo].[ModelosDocumento] ([IdModeloDocumento]),
    CONSTRAINT [FK_Relatorios_Usuarios] FOREIGN KEY ([IdUsuario]) REFERENCES [dbo].[Usuarios] ([IdUsuario])
);

