CREATE TABLE [dbo].[SolicitacoesViagem] (
    [IdSolicitacaoViagem]         INT            IDENTITY (1, 1) NOT NULL,
    [NumSolicitacaoViagem]        NVARCHAR (20)  NOT NULL,
    [DataSolicitacaoViagem]       DATETIME       NOT NULL,
    [IdPessoaSolicitante]         INT            NOT NULL,
    [IdEvento]                    INT            NULL,
    [NomeEvento]                  NVARCHAR (150) NULL,
    [DescricaoEvento]             NTEXT          NULL,
    [DataHoraInicioEvento]        DATETIME       NULL,
    [DataHoraFimEvento]           DATETIME       NULL,
    [UFEvento]                    CHAR (2)       NULL,
    [IdCidadeEvento]              INT            NULL,
    [URLReferenciaEvento]         NVARCHAR (150) NULL,
    [StatusSolicitacao]           NVARCHAR (50)  NULL,
    [IdSituacaoSolicitacaoAtual]  INT            NULL,
    [Observacoes]                 NTEXT          NULL,
    [E_SolicitacaoDiaria]         BIT            NULL,
    [AlertaEmpenho]               BIT            NULL,
    [IdPessoaAutorizador]         INT            NULL,
    [NumeroProjeto]               VARCHAR (80)   NULL,
    [IdProcessoSolicitacaoViagem] INT            NULL,
    [IdPessoaSolicitanteReal]     INT            NULL,
    CONSTRAINT [PK_SolicitacoesViagem] PRIMARY KEY CLUSTERED ([IdSolicitacaoViagem] ASC),
    CONSTRAINT [FK_SolicitacoesViagem_Cidades] FOREIGN KEY ([IdCidadeEvento]) REFERENCES [dbo].[Cidades] ([IdCidade]),
    CONSTRAINT [FK_SolicitacoesViagem_EventosSispad] FOREIGN KEY ([IdEvento]) REFERENCES [dbo].[EventosSispad] ([IdEvento]),
    CONSTRAINT [FK_SolicitacoesViagem_IdProcessoSolicitacaoViagem] FOREIGN KEY ([IdProcessoSolicitacaoViagem]) REFERENCES [dbo].[ProcessosSolicitacaoViagem] ([IdProcessoSolicitacaoViagem]),
    CONSTRAINT [FK_SolicitacoesViagem_PessoaAutorizador] FOREIGN KEY ([IdPessoaAutorizador]) REFERENCES [dbo].[PessoasSispad] ([IdPessoaSispad]),
    CONSTRAINT [FK_SolicitacoesViagem_Pessoas] FOREIGN KEY ([IdPessoaSolicitante]) REFERENCES [dbo].[PessoasSispad] ([IdPessoaSispad]),
    CONSTRAINT [FK_SolicitacoesViagem_PessoasSispad_IdPessoaSolicitanteReal] FOREIGN KEY ([IdPessoaSolicitanteReal]) REFERENCES [dbo].[PessoasSispad] ([IdPessoaSispad])
);

