CREATE TABLE [dbo].[Suspensoes] (
    [IdSuspensao]           INT          IDENTITY (1, 1) NOT NULL,
    [IdRepresentadoProf]    INT          NULL,
    [IdRepresentadoPessoa]  INT          NULL,
    [IdRepresentadoPJ]      INT          NULL,
    [IdProcesso]            INT          NULL,
    [Descricao]             TEXT         NULL,
    [DataInicio]            DATETIME     NULL,
    [DataFim]               DATETIME     NULL,
    [IdTipoSuspensao]       INT          NOT NULL,
    [DataTransacao]         DATETIME     NOT NULL,
    [Duracao]               INT          NULL,
    [QuantAnuidadeMulta]    INT          NULL,
    [ProrrogavelDebito]     BIT          CONSTRAINT [DF_Suspensoes_ProrrogavelDebito] DEFAULT ((0)) NOT NULL,
    [ProrrogavelOutros]     BIT          CONSTRAINT [DF_Suspensoes_ProrrogavelOutros] DEFAULT ((0)) NOT NULL,
    [IdSeccionalOrigem]     INT          NULL,
    [ProcessoOrigem]        VARCHAR (40) NULL,
    [DataJuntadaCarteira]   DATETIME     CONSTRAINT [DF_Suspensoes_JuntadaCarteira] DEFAULT ((0)) NULL,
    [DataRetiradaCarteira]  DATETIME     CONSTRAINT [DF_Suspensoes_RetiradaCarteira] DEFAULT ((0)) NULL,
    [JustificativaCarteira] TEXT         NULL,
    [IdUsuario]             INT          CONSTRAINT [DF_Suspensoes_IdUsuario] DEFAULT ((0)) NOT NULL,
    [IdDepartamento]        INT          CONSTRAINT [DF_Suspensoes_IdDepartamento] DEFAULT ((0)) NOT NULL,
    [idFaseFimVigencia]     INT          NULL,
    [ValorMultaPena]        MONEY        NULL,
    [DuracaoMeses]          INT          NULL,
    CONSTRAINT [PK_Suspensoes_Id] PRIMARY KEY CLUSTERED ([IdSuspensao] ASC),
    CONSTRAINT [FK_Suspensoes_Departamentos] FOREIGN KEY ([IdDepartamento]) REFERENCES [dbo].[Departamentos] ([IdDepto]),
    CONSTRAINT [FK_Suspensoes_Pessoas] FOREIGN KEY ([IdRepresentadoPessoa]) REFERENCES [dbo].[Pessoas] ([IdPessoa]),
    CONSTRAINT [FK_Suspensoes_Pessoas1] FOREIGN KEY ([IdSeccionalOrigem]) REFERENCES [dbo].[Pessoas] ([IdPessoa]),
    CONSTRAINT [FK_Suspensoes_PessoasJuridicas] FOREIGN KEY ([IdRepresentadoPJ]) REFERENCES [dbo].[PessoasJuridicas] ([IdPessoaJuridica]),
    CONSTRAINT [FK_Suspensoes_Processos] FOREIGN KEY ([IdProcesso]) REFERENCES [dbo].[Processos] ([IdProcesso]),
    CONSTRAINT [FK_Suspensoes_Profissionais] FOREIGN KEY ([IdRepresentadoProf]) REFERENCES [dbo].[Profissionais] ([IdProfissional]),
    CONSTRAINT [FK_Suspensoes_TiposSuspensao] FOREIGN KEY ([IdTipoSuspensao]) REFERENCES [dbo].[TiposSuspensao] ([IdTipoSuspensao]),
    CONSTRAINT [FK_Suspensoes_Usuarios] FOREIGN KEY ([IdUsuario]) REFERENCES [dbo].[Usuarios] ([IdUsuario])
);

