CREATE TABLE [dbo].[TelasDefinicoes] (
    [CodigoTela]            INT           NOT NULL,
    [NomeTabela]            CHAR (25)     NOT NULL,
    [NomeCampo]             CHAR (20)     NOT NULL,
    [TituloMonitor]         VARCHAR (40)  NULL,
    [TituloImpressora]      VARCHAR (40)  NULL,
    [TipoCampo]             CHAR (1)      NOT NULL,
    [DataMenor]             DATETIME      NULL,
    [DataMaior]             DATETIME      NULL,
    [DataAtualMenor]        BIT           NULL,
    [DataAtualMaior]        BIT           NULL,
    [AutoIncremental]       BIT           NULL,
    [NumMenor]              INT           NULL,
    [NumMaior]              INT           NULL,
    [ValorMenor]            MONEY         NULL,
    [ValorMaior]            MONEY         NULL,
    [PosicaoEsquerda]       INT           NULL,
    [PosicaoTopo]           INT           NULL,
    [NomeTabelaAux]         VARCHAR (40)  NULL,
    [UtilizarProf]          BIT           NULL,
    [UtilizarPJ]            BIT           NULL,
    [UtilizarPessoa]        BIT           NULL,
    [Filtrar1Prof]          INT           NULL,
    [Filtrar2Prof]          INT           NULL,
    [Filtrar3Prof]          INT           NULL,
    [Filtrar1PJ]            INT           NULL,
    [Filtrar2PJ]            INT           NULL,
    [Filtrar3PJ]            INT           NULL,
    [UtilizarParaConsulta]  BIT           NULL,
    [Posicao]               BIT           NULL,
    [Tamanho]               INT           NULL,
    [TopoProf]              BIT           NULL,
    [IdTipoProcesso]        INT           CONSTRAINT [DF_TelasDefinicoes_IdTipoProcesso] DEFAULT ((0)) NOT NULL,
    [OrdemGridFisc]         INT           NULL,
    [ColunasGrid]           VARCHAR (500) NULL,
    [TamanhoHorizontalGrid] INT           NULL,
    [ordemWeb]              INT           NULL,
    [VisualizarWeb]         BIT           NULL,
    [ExibirWeb]             BIT           NULL,
    [OrdemTab]              INT           NULL,
    [Obrigatorio]           BIT           NULL,
    [Filtrar1OP]            INT           NULL,
    [FiltrarFiscais]        BIT           NULL,
    [VinculaDA]             BIT           CONSTRAINT [DF_TelasDefinicoes_VinculaDA] DEFAULT ((0)) NOT NULL,
    [IdTelasDefinicao]      INT           IDENTITY (1, 1) NOT NULL
);

