CREATE TABLE [dbo].[TipoProcesso] (
    [IdTipoProcesso]                  INT          IDENTITY (1, 1) NOT NULL,
    [ProcessoTipo]                    VARCHAR (50) NOT NULL,
    [VisualizarWeb]                   BIT          NULL,
    [ModeloTipoProcesso]              VARCHAR (50) NULL,
    [ConfigProcInscricao]             INT          NULL,
    [FiscAutoIncProc]                 INT          NULL,
    [FiscPrefSufProc]                 INT          NULL,
    [VincularDocCriacao]              BIT          NULL,
    [PrefSufNumDoc_Processo]          INT          NULL,
    [TamNProc]                        INT          NULL,
    [ReiniciaAnoProc]                 INT          NULL,
    [REPETIRNUMEROPROC]               INT          NULL,
    [IdModeloDoc]                     INT          NULL,
    [AbasVisiveisProcesso]            VARCHAR (10) NULL,
    [OcorrenciasAlterarExcluir]       INT          NULL,
    [FasesAlterarExcluir]             INT          NULL,
    [ConfigProcInscricaoPJ]           INT          NULL,
    [ExibirTelaCadastro]              BIT          CONSTRAINT [DF__TipoProce__Exibi__0302CECB] DEFAULT ((0)) NOT NULL,
    [TramitacaoDocOrigem]             BIT          NULL,
    [SequencialProcesso]              BIGINT       NULL,
    [AnoProcesso]                     VARCHAR (4)  NULL,
    [DataAutuacaoAutomatica]          BIT          NULL,
    [ConfigMudancaProcessoPrescricao] INT          NULL,
    [Qtd]                             INT          DEFAULT ((0)) NULL,
    [Criterio]                        VARCHAR (5)  NULL,
    [TramitacoesProcEnviar]           INT          NULL,
    [TramitacoesProcReceber]          INT          NULL,
    [TramitacoesProcAlterar]          INT          NULL,
    [TramitacoesProcAlterarExt]       INT          NULL,
    [TramitacoesProcFiltrarRespLocal] BIT          NULL,
    [PrioridadePadrao]                INT          NULL,
    [SituacaoPadrao]                  INT          NULL,
    [UtilizarUsuarioPadrao]           BIT          NULL,
    [LiberarEnvioTramitacao]          BIT          NULL,
    [ResumoDebitoVinculado]           BIT          NULL,
    [ReiniciarAnoProc]                BIT          NULL,
    [CriaProcessoFiscal]              BIT          DEFAULT ((0)) NOT NULL,
    [NrProcessoZeroEsq]               BIT          CONSTRAINT [DEF_TipoProcessoNrProcessoZeroEsq] DEFAULT ((1)) NOT NULL,
    [PrefSufAdicional]                VARCHAR (25) NULL,
    [UltimoNumeroPasta]               INT          NULL,
    [NumProcExtPermitirAlfaNum]       BIT          CONSTRAINT [DEF_TipoProcesso_NumProcExtPermitirAltaNum] DEFAULT ((1)) NOT NULL,
    [VincularDA]                      BIT          CONSTRAINT [Vincular_DA] DEFAULT ((1)) NOT NULL,
    [VincularCategoriaInscricaoPF]    BIT          CONSTRAINT [DEF_VincularCategoriaInscricaoPF] DEFAULT ((0)) NOT NULL,
    [VincularCategoriaInscricaoPJ]    BIT          CONSTRAINT [DEF_VincularCategoriaInscricaoPJ] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TipoProcesso] PRIMARY KEY CLUSTERED ([IdTipoProcesso] ASC)
);

