CREATE TABLE [dbo].[TiposDocumentos] (
    [IdTipoDocumento]                 INT          IDENTITY (1, 1) NOT NULL,
    [TipoDocumento]                   VARCHAR (40) NOT NULL,
    [SiglaDocumento]                  VARCHAR (15) NULL,
    [IdFuncao]                        INT          NULL,
    [UsaMascaraNumeracao]             BIT          NULL,
    [Prefixo]                         VARCHAR (20) NULL,
    [Sufixo]                          VARCHAR (20) NULL,
    [TipoNumeracaoAutomatica]         INT          NULL,
    [TamanhoNumeroAuto]               INT          NULL,
    [UsoExclusivo]                    BIT          NULL,
    [IndCriacao]                      CHAR (1)     NULL,
    [ReiniciaNumeracaoAnual]          BIT          NULL,
    [AceitaNumeracaoDuplicada]        BIT          NULL,
    [AutoIncDocsEntradas]             BIT          NULL,
    [AutoIncDocsSaidas]               BIT          NULL,
    [AutoIncDocsInternos]             BIT          NULL,
    [VisualizaroutrosModulos]         BIT          CONSTRAINT [DF_TiposDocumentos_VisualizaroutrosModulos] DEFAULT ((0)) NULL,
    [Desativado]                      BIT          CONSTRAINT [DF_TiposDocumentosDesativado] DEFAULT ((0)) NULL,
    [VincularDebitos]                 BIT          CONSTRAINT [DF_TiposDocumentosVincularDebitos] DEFAULT ((0)) NULL,
    [ExibirMenuModelo]                BIT          NULL,
    [IdSituacaoDocumento]             INT          NULL,
    [VerificarNivelConfidencialidade] BIT          DEFAULT ((0)) NOT NULL,
    [GravarSomenteNumeroCampoNrDoc]   BIT          CONSTRAINT [DF_TiposDocumentos_GravarSomenteNumeroCampoNrDoc] DEFAULT ((0)) NULL,
    [IndOrigemDoc]                    CHAR (1)     NULL,
    [AutoIncDocsTodos]                BIT          DEFAULT ((0)) NOT NULL,
    [ExigirRegistrado]                INT          CONSTRAINT [DEF_TiposDocumentos_ExigirRegistrado] DEFAULT ((0)) NOT NULL,
    [NumUnicaUtilizar]                BIT          CONSTRAINT [DEF_TiposDocumentos_NumUnicaUtilizar] DEFAULT ((0)) NOT NULL,
    [IdFormaNotificacao]              INT          NULL,
    [IdFormaEntregaDocumento]         INT          NULL,
    [PrazoEntrada]                    INT          NULL,
    [PrazoSaida]                      INT          NULL,
    [UnidadePrazoEntrada]             CHAR (1)     DEFAULT ('D') NULL,
    [UnidadePrazoSaida]               CHAR (1)     DEFAULT ('D') NULL,
    [IdClassificacaoDocumento]        INT          NULL,
    CONSTRAINT [PK_TiposDocumentos] PRIMARY KEY CLUSTERED ([IdTipoDocumento] ASC),
    CONSTRAINT [FK_SituacoesDocumento] FOREIGN KEY ([IdSituacaoDocumento]) REFERENCES [dbo].[SituacoesDocumento] ([IdSituacaoDocumento]),
    CONSTRAINT [FK_TiposDocumentos_ClassificacaoDocumento] FOREIGN KEY ([IdClassificacaoDocumento]) REFERENCES [dbo].[ClassificacaoDocumentos] ([IdClassificacaoDocumento]),
    CONSTRAINT [FK_TiposDocumentos_FuncoesSiscafw] FOREIGN KEY ([IdFuncao]) REFERENCES [dbo].[FuncoesSiscafw] ([IdFuncao]),
    CONSTRAINT [FK_TiposDocumentos_IdFormaEntregaDocumento] FOREIGN KEY ([IdFormaEntregaDocumento]) REFERENCES [dbo].[FormaEntregaDocumento] ([idFormaEntregaDocumento]),
    CONSTRAINT [FK_TiposDocumentos_IdFormaNotificacao] FOREIGN KEY ([IdFormaNotificacao]) REFERENCES [dbo].[FormasNotificacao] ([IdFormaNotificacao])
);

