CREATE TABLE [dbo].[TipoFiscalizacao] (
    [IdTipoFiscalizacao]                 INT           IDENTITY (1, 1) NOT NULL,
    [Descricao]                          VARCHAR (100) NULL,
    [ModeloTipoFiscalizacao]             VARCHAR (50)  NULL,
    [FiscAutoInc]                        INT           NULL,
    [ReiniciaAno]                        INT           NULL,
    [FiscPrefSuf]                        INT           NULL,
    [campoCabecalhoFisc]                 VARCHAR (50)  NULL,
    [FiscTamanhoSequencial]              INT           NULL,
    [FiscSigla]                          VARCHAR (4)   NULL,
    [FiscalizacaoCaptionAbaDinamica]     VARCHAR (50)  NULL,
    [FiscalizacaoNomeDinamico1]          VARCHAR (25)  NULL,
    [FiscalizacaoNomeDinamico2]          VARCHAR (25)  NULL,
    [FiscalizacaoNomeDinamico3]          VARCHAR (25)  NULL,
    [FiscalizacaoCaptionAbaDinamicaFisc] VARCHAR (50)  NULL,
    [Desativado]                         BIT           CONSTRAINT [DEF_TipoFiscalizacao_Desativado] DEFAULT ((0)) NOT NULL,
    [IdSituacaoFisc]                     INT           NULL,
    [Observacoes]                        TEXT          NULL,
    [IdFiscalPessoa]                     INT           NULL,
    [IdFiscalProf]                       INT           NULL,
    [IdAndamento]                        INT           NULL,
    [Alfa1Fisc]                          VARCHAR (40)  NULL,
    [Alfa2Fisc]                          VARCHAR (40)  NULL,
    [Alfa3Fisc]                          VARCHAR (40)  NULL,
    [Alfa4Fisc]                          VARCHAR (40)  NULL,
    [Alfa5Fisc]                          VARCHAR (40)  NULL,
    [Alfa6Fisc]                          VARCHAR (40)  NULL,
    [Alfa7Fisc]                          VARCHAR (40)  NULL,
    [Alfa8Fisc]                          VARCHAR (40)  NULL,
    [Alfa9Fisc]                          VARCHAR (40)  NULL,
    [Alfa10Fisc]                         VARCHAR (40)  NULL,
    [chk1Fisc]                           BIT           CONSTRAINT [DEF_TipoFiscalizacao_chk1Fisc] DEFAULT ((0)) NOT NULL,
    [chk2Fisc]                           BIT           CONSTRAINT [DEF_TipoFiscalizacao_chk2Fisc] DEFAULT ((0)) NOT NULL,
    [chk3Fisc]                           BIT           CONSTRAINT [DEF_TipoFiscalizacao_chk3Fisc] DEFAULT ((0)) NOT NULL,
    [chk4Fisc]                           BIT           CONSTRAINT [DEF_TipoFiscalizacao_chk4Fisc] DEFAULT ((0)) NOT NULL,
    [chk5Fisc]                           BIT           CONSTRAINT [DEF_TipoFiscalizacao_chk5Fisc] DEFAULT ((0)) NOT NULL,
    [chk6Fisc]                           BIT           CONSTRAINT [DEF_TipoFiscalizacao_chk6Fisc] DEFAULT ((0)) NOT NULL,
    [Data1Fisc]                          DATETIME      NULL,
    [Data2Fisc]                          DATETIME      NULL,
    [Data3Fisc]                          DATETIME      NULL,
    [Data4Fisc]                          DATETIME      NULL,
    [IdCidade1]                          INT           NULL,
    [IdCidade2]                          INT           NULL,
    [IdTabela1Fisc]                      INT           NULL,
    [IdTabela2Fisc]                      INT           NULL,
    [IdTabela3Fisc]                      INT           NULL,
    [IdTabela4Fisc]                      INT           NULL,
    [IdTabela5Fisc]                      INT           NULL,
    [IdUF1]                              INT           NULL,
    [IdUF2]                              INT           NULL,
    [Num1Fisc]                           INT           NULL,
    [Num2Fisc]                           INT           NULL,
    [Num3Fisc]                           INT           NULL,
    [Num4Fisc]                           INT           NULL,
    [Num5Fisc]                           INT           NULL,
    [Valor1Fisc]                         MONEY         NULL,
    [Valor2Fisc]                         MONEY         NULL,
    [Valor3Fisc]                         MONEY         NULL,
    [ExibirCampoAtuacao]                 BIT           CONSTRAINT [DEF_TipoFiscalizacao_ExibirCampoAtuacao] DEFAULT ((0)) NOT NULL,
    [ExibirCampoFuncao]                  BIT           CONSTRAINT [DEF_TipoFiscalizacao_ExibirCampoFuncao] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TipoFiscalizacao_IdTipoFiscalizacao] PRIMARY KEY CLUSTERED ([IdTipoFiscalizacao] ASC),
    CONSTRAINT [FK_TipoFiscalizacao_Fases] FOREIGN KEY ([IdAndamento]) REFERENCES [dbo].[Fases] ([IdFase]),
    CONSTRAINT [FK_TipoFiscalizacao_Pessoas] FOREIGN KEY ([IdFiscalPessoa]) REFERENCES [dbo].[Pessoas] ([IdPessoa]),
    CONSTRAINT [FK_TipoFiscalizacao_Profissionais] FOREIGN KEY ([IdFiscalProf]) REFERENCES [dbo].[Profissionais] ([IdProfissional]),
    CONSTRAINT [FK_TipoFiscalizacao_SituacoesProcFis] FOREIGN KEY ([IdSituacaoFisc]) REFERENCES [dbo].[SituacoesProcFis] ([IdSituacaoProcFis])
);

