CREATE TABLE [dbo].[TrechosPessoasSolicitacoesViagem] (
    [IdTrechoPessoaSolicitacaoViagem] INT            IDENTITY (1, 1) NOT NULL,
    [IdPessoaSolicitacaoViagem]       INT            NOT NULL,
    [IdCidadeOrigem]                  INT            NULL,
    [IdEstadoOrigem]                  INT            NULL,
    [IdCidadeDestino]                 INT            NULL,
    [IdEstadoDestino]                 INT            NULL,
    [MeioTransporte]                  INT            NOT NULL,
    [DataTrecho]                      DATETIME       NULL,
    [SugestaoHora1]                   DATETIME       NULL,
    [SugestaoHora2]                   DATETIME       NULL,
    [ObservacaoTrecho]                TEXT           NULL,
    [Confirmacao]                     BIT            NULL,
    [IdPessoaCompanhia]               INT            NULL,
    [DistanciaTrecho]                 FLOAT (53)     NULL,
    [DistanciaInformada]              BIT            NULL,
    [DistanciaFonte]                  NVARCHAR (100) NULL,
    [LocalRetirada]                   TEXT           NULL,
    [LocalEntrega]                    TEXT           NULL,
    [IdCategoriaVeiculo]              INT            NULL,
    [IdPessoaLocadora]                INT            NULL,
    [ComMotorista]                    BIT            NULL,
    [PassagemAerea]                   BIT            NULL,
    [Tipo]                            CHAR (1)       NULL,
    [LocalOrigem]                     VARCHAR (200)  NULL,
    [LocalDestino]                    VARCHAR (200)  NULL,
    CONSTRAINT [PK_TrechosPessoasSolicitacoesViagem] PRIMARY KEY CLUSTERED ([IdTrechoPessoaSolicitacaoViagem] ASC),
    CONSTRAINT [FK_TrechosPessoasSolicitacoesViagem_CategoriasVeiculo] FOREIGN KEY ([IdCategoriaVeiculo]) REFERENCES [dbo].[CategoriasVeiculo] ([IdCategoriaVeiculo]),
    CONSTRAINT [FK_TrechosPessoasSolicitacoesViagem_Cidades] FOREIGN KEY ([IdCidadeOrigem]) REFERENCES [dbo].[Cidades] ([IdCidade]),
    CONSTRAINT [FK_TrechosPessoasSolicitacoesViagem_Cidades1] FOREIGN KEY ([IdCidadeDestino]) REFERENCES [dbo].[Cidades] ([IdCidade]),
    CONSTRAINT [FK_TrechosPessoasSolicitacoesViagem_Estados] FOREIGN KEY ([IdEstadoOrigem]) REFERENCES [dbo].[Estados] ([IdEstado]),
    CONSTRAINT [FK_TrechosPessoasSolicitacoesViagem_Estados1] FOREIGN KEY ([IdEstadoDestino]) REFERENCES [dbo].[Estados] ([IdEstado]),
    CONSTRAINT [FK_TrechosPessoasSolicitacoesViagem_LocadorasVeiculo] FOREIGN KEY ([IdPessoaLocadora]) REFERENCES [dbo].[Locadoras] ([IdPessoaLocadora]),
    CONSTRAINT [FK_TrechosPessoasSolicitacoesViagem_Pessoas] FOREIGN KEY ([IdPessoaCompanhia]) REFERENCES [dbo].[Companhias] ([IdPessoaCompanhia]),
    CONSTRAINT [FK_TrechosPessoasSolicitacoesViagem_PessoasSolicitacoesViagem] FOREIGN KEY ([IdPessoaSolicitacaoViagem]) REFERENCES [dbo].[PessoasSolicitacoesViagem] ([IdPessoaSolicitacaoViagem])
);

