CREATE TABLE [dbo].[Usuarios] (
    [IdUsuario]               INT            IDENTITY (1, 1) NOT NULL,
    [IdPerfil]                INT            NULL,
    [IdPessoa]                INT            NULL,
    [NomeUsuario]             VARCHAR (30)   NULL,
    [Senha]                   CHAR (20)      NOT NULL,
    [IdResponsavel]           INT            NULL,
    [DataValidadeSenha]       DATETIME       NULL,
    [DataExpiracaoSenha]      DATETIME       NULL,
    [PrazoExpiracao]          INT            NULL,
    [BaixaAtualizacoes]       BIT            NULL,
    [UltimaVersaoLogon]       VARCHAR (20)   NULL,
    [IdDepartamento]          INT            NULL,
    [ATIVO]                   BIT            NULL,
    [UsuarioTransferido]      BIT            CONSTRAINT [DF__usuarios__Usuari__56E1280F] DEFAULT ((0)) NULL,
    [IdCentroCusto]           INT            NULL,
    [IdCentroCustoReceita]    INT            NULL,
    [NomeContaPersonalizada]  VARCHAR (60)   NULL,
    [IdProfissionalNome]      INT            NULL,
    [IdPessoaJuridicaNome]    INT            NULL,
    [IdPessoaNome]            INT            NULL,
    [MatriculaUsuario]        VARCHAR (30)   NULL,
    [Email]                   NVARCHAR (150) NULL,
    [AssinaturaDigital]       IMAGE          NULL,
    [Assinatura]              NVARCHAR (250) NULL,
    [Cargo]                   NVARCHAR (250) NULL,
    [Registro]                NVARCHAR (250) NULL,
    [CPF]                     NVARCHAR (250) NULL,
    [DataUltimoAcessoSiscafw] DATETIME       NULL,
    [LoginWindows]            VARCHAR (30)   NULL,
    [AssinaturaEmail]         VARCHAR (2000) NULL,
    [AssinaturaEmailURLImg]   VARCHAR (250)  NULL,
    [DataUltimoAcessoLogon]   DATETIME       NULL,
    [DataMensagemInfo]        DATETIME       NULL,
    [EmailBackup]             VARCHAR (100)  NULL,
    [EnviaEmailBackup]        BIT            CONSTRAINT [DF_Usuarios_EnviaEmailBackup] DEFAULT ((0)) NOT NULL,
    [idPessoaSispad]          INT            NULL,
    CONSTRAINT [PK_Usuarios] PRIMARY KEY NONCLUSTERED ([IdUsuario] ASC),
    CONSTRAINT [FK_Usuarios_Departamentos] FOREIGN KEY ([IdDepartamento]) REFERENCES [dbo].[Departamentos] ([IdDepto]),
    CONSTRAINT [FK_Usuarios_IdPessoaJuridicaNome] FOREIGN KEY ([IdPessoaJuridicaNome]) REFERENCES [dbo].[PessoasJuridicas] ([IdPessoaJuridica]),
    CONSTRAINT [FK_Usuarios_IdPessoaNome] FOREIGN KEY ([IdPessoaNome]) REFERENCES [dbo].[Pessoas] ([IdPessoa]),
    CONSTRAINT [FK_Usuarios_IdProfissionalNome] FOREIGN KEY ([IdProfissionalNome]) REFERENCES [dbo].[Profissionais] ([IdProfissional]),
    CONSTRAINT [FK_Usuarios_PerfisLogon] FOREIGN KEY ([IdPerfil]) REFERENCES [dbo].[PerfisLogon] ([IdPerfil]),
    CONSTRAINT [FK_Usuarios_Pessoas_Conselho] FOREIGN KEY ([IdPessoa]) REFERENCES [dbo].[Pessoas] ([IdPessoa]) NOT FOR REPLICATION
);

