CREATE TABLE [dbo].[Web_DetalhesEmissao] (
    [IdWeb_DetalhesEmissao]   INT            IDENTITY (1, 1) NOT NULL,
    [IdDetalheEmissao]        INT            NOT NULL,
    [IdEmissao]               INT            NULL,
    [IdMoedaDevida]           INT            NULL,
    [NossoNumero]             VARCHAR (20)   NULL,
    [DataEmissao]             DATETIME       NOT NULL,
    [DataVencimento]          DATETIME       NULL,
    [DataAtualizacaoEncargos] DATETIME       NULL,
    [ValorEmissao]            MONEY          NULL,
    [ValorDespBco]            MONEY          NULL,
    [ValorDespAdv]            MONEY          NULL,
    [ValorDespPostais]        MONEY          NULL,
    [TipoEmissao]             INT            NULL,
    [TipoComposicao]          INT            NULL,
    [CodBanco]                VARCHAR (3)    NULL,
    [CodAgencia]              VARCHAR (4)    NULL,
    [CodOperacao]             VARCHAR (3)    NULL,
    [CodCC_Conv_Ced]          VARCHAR (16)   NULL,
    [AtualizacaoWeb]          VARCHAR (5000) NULL,
    [IndAtualizacao]          BIT            NULL,
    [DataBaixa]               DATETIME       NULL,
    [RegistraLog]             BIT            CONSTRAINT [DF__DetalhesE__Regis__0623C4D8_WEB] DEFAULT ((1)) NULL,
    [bValorComDesconto]       BIT            NULL,
    [SeuNumero]               CHAR (11)      NULL,
    [DescontoAplicado]        BIT            CONSTRAINT [DF_DetalhesEmissao_DescontoAplicado_WEB] DEFAULT ((0)) NOT NULL,
    [SituacaoRegistro]        INT            CONSTRAINT [DF_DetalhesEmissao_SituacaoRegistro_WEB] DEFAULT ((1)) NOT NULL,
    [IdConfigRegistro]        INT            NULL,
    [IdMsgBoletoBancarioI]    INT            NULL,
    [IdMsgBoletoBancarioM]    INT            NULL,
    [InstrIdentifSim]         BIT            CONSTRAINT [DF_DetalhesEmissao_InstrIdentifSim_WEB] DEFAULT ((0)) NOT NULL,
    [IdEmissaoConfig]         INT            NULL,
    [CodMotivoOcorrencia]     VARCHAR (2)    NULL
);

