CREATE TABLE [dbo].[Web_Enderecos] (
    [IdWeb_Endereco]                INT            IDENTITY (1, 1) NOT NULL,
    [IdEndereco]                    INT            NOT NULL,
    [IdProfissional]                INT            NULL,
    [Endereco]                      VARCHAR (272)  NULL,
    [NomeBairro]                    VARCHAR (35)   NULL,
    [NomeCidade]                    VARCHAR (30)   NULL,
    [SiglaUf]                       CHAR (2)       NULL,
    [CEP]                           VARCHAR (8)    NULL,
    [E_Exterior]                    BIT            NULL,
    [E_Residencial]                 INT            CONSTRAINT [DF_Web_Enderecos_E_Residencial] DEFAULT ((1)) NULL,
    [Correspondencia]               BIT            NULL,
    [Atualizado]                    BIT            NULL,
    [DataUltimaAtualizacao]         DATETIME       NULL,
    [CaixaPostal]                   VARCHAR (15)   NULL,
    [AtualizacaoWeb]                VARCHAR (5000) NULL,
    [IndAtualizacao]                BIT            NULL,
    [DataBaixa]                     DATETIME       NULL,
    [DataAtualizacao]               DATETIME       NULL,
    [UsuarioUltimaAtualizacao]      VARCHAR (35)   NULL,
    [DepartamentoUltimaAtualizacao] VARCHAR (60)   NULL,
    [idSiscafWeb]                   INT            NULL,
    [IdPessoa]                      INT            NULL,
    [OrdemCorresp]                  INT            NULL,
    [OrdemDtAtualiz]                DATETIME       NULL,
    [CORRESPONDENCIAPROCESSO]       BIT            CONSTRAINT [DF__ENDERECOS__CORRE__057A84B9_WEB] DEFAULT ((0)) NOT NULL,
    [IdPJTrabalho]                  INT            NULL,
    [E_Divulgacao]                  BIT            NULL,
    [MalaDireta]                    BIT            NULL,
    [Observacao]                    VARCHAR (8000) NULL,
    [IdPais]                        INT            NULL,
    [ComplementoEndereco]           VARCHAR (8000) NULL,
    [IdPessoaJuridica]              INT            NULL,
    [Numero]                        VARCHAR (10)   NULL,
    [SessaoWeb]                     VARCHAR (50)   NULL,
    [Endereco1]                     VARCHAR (200)  NULL,
    [Logradouro]                    VARCHAR (60)   NULL,
    CONSTRAINT [PK_Web_Enderecos] PRIMARY KEY CLUSTERED ([IdWeb_Endereco] ASC)
);

