CREATE TABLE [dbo].[Web_Profissionais] (
    [IdWeb_Profissional]          INT            IDENTITY (1, 1) NOT NULL,
    [IdProfissional]              INT            NOT NULL,
    [IdUnidadeConselho]           INT            NULL,
    [IdSubRegiao]                 INT            NULL,
    [IdTipoInscricao]             INT            NULL,
    [IdReligiao]                  INT            NULL,
    [IdCidadeNaturalidade]        INT            NULL,
    [IdNacionalidade]             INT            NULL,
    [CategoriaAtual]              VARCHAR (40)   NULL,
    [SituacaoAtual]               VARCHAR (50)   NULL,
    [Nome]                        VARCHAR (100)  NULL,
    [RegistroConselhoAtual]       VARCHAR (20)   NULL,
    [NomeBairro]                  VARCHAR (50)   NULL,
    [NomeCidade]                  VARCHAR (30)   NULL,
    [SiglaUF]                     VARCHAR (2)    NULL,
    [SiglaUFNaturalidade]         CHAR (2)       NULL,
    [Endereco]                    VARCHAR (60)   NULL,
    [CEP]                         VARCHAR (8)    NULL,
    [E_Exterior]                  BIT            NULL,
    [E_Residencial]               INT            NULL,
    [Atualizado]                  BIT            NULL,
    [DataInscricaoConselho]       DATETIME       NULL,
    [DataUltimaAtualizacao]       DATETIME       NULL,
    [Sexo]                        VARCHAR (1)    NULL,
    [DataNascimento]              DATETIME       NULL,
    [TipoSanguineo]               VARCHAR (3)    NULL,
    [CPF]                         VARCHAR (11)   NULL,
    [CTPS]                        VARCHAR (10)   NULL,
    [SerieCTPS]                   VARCHAR (5)    NULL,
    [RG]                          VARCHAR (15)   NULL,
    [RGDataEmissao]               DATETIME       NULL,
    [RGOrgaoEmissao]              VARCHAR (20)   NULL,
    [SiglaUFRG]                   CHAR (2)       NULL,
    [TipoCarteiraIdentidade]      VARCHAR (1)    NULL,
    [CertificadoReserv]           VARCHAR (15)   NULL,
    [CertificadoReservCSM]        VARCHAR (11)   NULL,
    [CertificadoReservData]       DATETIME       NULL,
    [Civil_Militar]               VARCHAR (1)    NULL,
    [TituloEleitorInscricao]      VARCHAR (13)   NULL,
    [TituloEleitorZona]           VARCHAR (3)    NULL,
    [TituloEleitorSecao]          VARCHAR (4)    NULL,
    [TituloEleitorDataEmissao]    DATETIME       NULL,
    [NomeCidadeTitEleitor]        VARCHAR (30)   NULL,
    [SiglaUFTituloEleitor]        CHAR (2)       NULL,
    [NomePai]                     VARCHAR (50)   NULL,
    [NomeMae]                     VARCHAR (50)   NULL,
    [Fotografia]                  BIT            NULL,
    [Raca]                        VARCHAR (1)    NULL,
    [EstadoCivil]                 VARCHAR (1)    NULL,
    [EnderecoEMail]               VARCHAR (90)   NULL,
    [TelefoneResid]               VARCHAR (100)  NULL,
    [TelefoneTrab]                VARCHAR (100)  NULL,
    [Processo]                    VARCHAR (15)   NULL,
    [E_Fiscal]                    BIT            NULL,
    [ExibirDadosWeb]              BIT            NULL,
    [Observacoes]                 VARCHAR (8000) NULL,
    [EnderecoEMail2]              VARCHAR (90)   NULL,
    [Site]                        VARCHAR (300)  NULL,
    [Site2]                       VARCHAR (300)  NULL,
    [RNE]                         VARCHAR (20)   NULL,
    [NomeConjuge]                 VARCHAR (50)   NULL,
    [CaixaPostal]                 VARCHAR (15)   NULL,
    [IndicativoProf1]             BIT            NULL,
    [IndicativoProf2]             BIT            NULL,
    [IndicativoProf3]             BIT            NULL,
    [AtualizacaoWeb]              VARCHAR (5000) NULL,
    [IndAtualizacao]              BIT            NULL,
    [DataBaixa]                   DATETIME       NULL,
    [DataAtualizacao]             DATETIME       NULL,
    [SiteDivulgacao]              BIT            NULL,
    [Site2Divulgacao]             BIT            NULL,
    [EmailDivulgacao]             BIT            NULL,
    [Email2Divulgacao]            BIT            NULL,
    [TelResidDivulgacao]          BIT            NULL,
    [TelCelDivulgacao]            BIT            NULL,
    [TelTrabDivulgacao]           BIT            NULL,
    [TelRecadoFaxDivulgacao]      BIT            NULL,
    [TelefoneCelular]             VARCHAR (100)  NULL,
    [TelefoneOutros]              VARCHAR (100)  NULL,
    [DtUltimaAtualizacaoContato]  DATETIME       NULL,
    [UsuUltimaAtualizacaoContato] VARCHAR (150)  NULL,
    [NomeSocial]                  VARCHAR (50)   NULL,
    [DepUltimaAtualizacaoContato] VARCHAR (60)   NULL,
    [idSiscafWeb]                 INT            NULL,
    [DoadorOrgaos]                BIT            NULL,
    [IdProfissionalOld]           INT            NULL,
    [DataInclusaoEmail]           DATETIME       NULL,
    [Livro]                       VARCHAR (10)   NULL,
    [Folha]                       VARCHAR (10)   NULL,
    [AlfaOutros1]                 VARCHAR (80)   NULL,
    [CodigoBarras]                VARCHAR (16)   NULL,
    [IdTabela1Prof]               INT            NULL,
    [idTabela1Profission]         INT            NULL,
    [IndicativoProf4]             BIT            NULL,
    [IndicativoProf5]             BIT            NULL,
    [IndicativoProf6]             BIT            NULL,
    [Data1prof]                   DATETIME       NULL,
    [Data2Prof]                   DATETIME       NULL,
    [IdDetalhePessoa1]            INT            NULL,
    [IdDetalhePessoa2]            INT            NULL,
    [IdDetalhePessoa3]            INT            NULL,
    [IdDetalhePessoa4]            INT            NULL,
    [IdDetalhePessoa5]            INT            NULL,
    [data3Prof]                   DATETIME       NULL,
    [data4Prof]                   DATETIME       NULL,
    [Deficiente]                  BIT            NULL,
    [IdDeficiencia]               INT            NULL,
    [AlfaOutros2]                 VARCHAR (80)   NULL,
    [AlfaOutros3]                 VARCHAR (80)   NULL,
    [AlfaOutros4]                 VARCHAR (80)   NULL,
    [Deficiencia]                 VARCHAR (100)  NULL,
    [data5Prof]                   DATETIME       NULL,
    [data6Prof]                   DATETIME       NULL,
    [Alfa1Prof]                   VARCHAR (80)   NULL,
    [AgenciaDebitoConta]          VARCHAR (5)    NULL,
    [ContaDebitoConta]            VARCHAR (15)   NULL,
    [E_Relator]                   BIT            NULL,
    [E_Instrutor]                 BIT            NULL,
    [DataUltExportacao]           DATETIME       NULL,
    [DataCompromisso]             DATETIME       NULL,
    [NumeroSeguranca]             INT            NULL,
    [IdBancoDebitoConta]          INT            NULL,
    [Codigo]                      VARCHAR (10)   NULL,
    [Classe]                      VARCHAR (1)    NULL,
    [NomeUsuario]                 VARCHAR (30)   NULL,
    [DepartamentoUsuario]         VARCHAR (60)   NULL,
    [AssinaDocumentos]            BIT            NULL,
    [NomeAbreviadoCarteiraEst]    VARCHAR (100)  NULL,
    [NomeMaeAbreviadoCarteiraEst] VARCHAR (50)   NULL,
    [NomePaiAbreviadoCarteiraEst] VARCHAR (50)   NULL,
    [IdPaisEndereco]              INT            NULL,
    [ComplementoEndereco]         VARCHAR (8000) NULL,
    [DataAlteracaoArqTJ]          DATETIME       NULL,
    [IdRegiaoAdministrativa]      INT            NULL,
    [IdOrigemInscricao]           INT            NULL,
    [IdUsuarioCriacao]            INT            NULL,
    [IdDepartamentoCriacao]       INT            NULL,
    [IdDelegaciaCriacao]          INT            NULL,
    [CertificadoReservOrgao]      VARCHAR (30)   NULL,
    [AnuidadeDiferenciada]        BIT            CONSTRAINT [DF__Profissio__Anuid__32E7E938_WEB] DEFAULT ((0)) NOT NULL,
    [TelefoneTrabCelular]         VARCHAR (100)  NULL,
    [CNABloquearEnvio]            BIT            CONSTRAINT [DEF_Profissionais_CNABloquearEnvio_WEB] DEFAULT ((0)) NOT NULL,
    [CorrespondenciaEmail]        BIT            CONSTRAINT [DEF_Profissionais_CorrespondenciaEmail_WEB] DEFAULT ((0)) NOT NULL,
    [TelCelTrabDivulgacao]        BIT            NULL,
    [TelTrabOutrosDivulgacao]     BIT            NULL,
    [RedesSociais]                VARCHAR (1000) NULL,
    [DataPedidoInscricao]         DATETIME       NULL,
    [suspenso]                    BIT            CONSTRAINT [DF__Profissio__suspe__5B36CED5_WEB] DEFAULT ((0)) NOT NULL,
    [E_Divulgacao]                BIT            NULL,
    [NaoPossuiMaeRG]              BIT            CONSTRAINT [DF_Profissionais_NaoPossuiMaeRG_WEB] DEFAULT ((0)) NOT NULL,
    [NaoPossuiPaiRG]              BIT            CONSTRAINT [DF_Profissionais_NaoPossuiPaiRG_WEB] DEFAULT ((0)) NOT NULL,
    [ExportacaoArquivoXMLCONFEN]  BIT            CONSTRAINT [DEF_ProfissionaisExportacaoArquivoXMLCONFEN_WEB] DEFAULT ((0)) NOT NULL,
    [DtUltimaAtualizacaoWeb]      DATETIME       NULL,
    [UsrUltimaAtualizacaoWeb]     VARCHAR (150)  NULL,
    [IdentGenero]                 INT            NULL,
    [DescIdentGenero]             VARCHAR (30)   NULL,
    CONSTRAINT [PK_Web_Profissionais] PRIMARY KEY CLUSTERED ([IdWeb_Profissional] ASC)
);

