CREATE TABLE [dbo].[Web_Receitas] (
    [IdReceita]                 INT            IDENTITY (1, 1) NOT NULL,
    [IdCentroCusto]             INT            NOT NULL,
    [IdCentroCustoReceita]      INT            NULL,
    [IdConta]                   INT            NOT NULL,
    [IdUsuarioSubSecao]         INT            NOT NULL,
    [IdUsuarioSIPRO]            INT            NULL,
    [DataReceita]               DATETIME       NOT NULL,
    [Quantidade]                INT            NOT NULL,
    [ValorTotal]                MONEY          NOT NULL,
    [Documento]                 VARCHAR (50)   NOT NULL,
    [Historico]                 VARCHAR (5000) NULL,
    [Status]                    VARCHAR (20)   NULL,
    [JustificativaRecusa]       VARCHAR (500)  NULL,
    [IdContaFinanceira]         INT            NULL,
    [NumeroReceita]             INT            NOT NULL,
    [AnoExercicio]              SMALLINT       NOT NULL,
    [ValorReceita]              MONEY          NULL,
    [ValorCustoReceita]         MONEY          NOT NULL,
    [QtdReceita]                INT            NOT NULL,
    [NumeroDocumento]           INT            NULL,
    [IdContaBanco]              INT            NOT NULL,
    [ValorUnitario]             MONEY          NULL,
    [IdLancamento]              INT            NULL,
    [Estornado]                 BIT            NOT NULL,
    [DataImportacao]            DATETIME       NULL,
    [Origem]                    VARCHAR (60)   NULL,
    [Conciliado]                BIT            NULL,
    [DataPrevisao]              DATETIME       NULL,
    [ValorPrevisao]             MONEY          NULL,
    [NumeroProcesso]            VARCHAR (20)   NULL,
    [AgrupamentoContabilizacao] INT            NULL,
    [IdFormaPagamento]          INT            NULL,
    [CobrancaCompartilhada]     BIT            CONSTRAINT [DF__Receitas__Cobran__3378BB98_WEB] DEFAULT ((0)) NOT NULL,
    [IdWebReceita]              INT            NULL,
    [IdReceitaARealizar]        INT            NULL,
    [RegistraLog]               BIT            CONSTRAINT [DF__Receitas__Regist__3C2D639D_WEB] DEFAULT ('1') NULL,
    [IdItemDevolucaoReceita]    INT            NULL,
    CONSTRAINT [PK_Web_Receitas] PRIMARY KEY CLUSTERED ([IdReceita] ASC),
    CONSTRAINT [FK_Web_Receitas_CentroCustos] FOREIGN KEY ([IdCentroCusto]) REFERENCES [dbo].[CentroCustos] ([IdCentroCusto]),
    CONSTRAINT [FK_Web_Receitas_CentroCustosReceita] FOREIGN KEY ([IdCentroCustoReceita]) REFERENCES [dbo].[CentroCustosReceita] ([IdCentroCustoReceita]),
    CONSTRAINT [FK_Web_Receitas_PlanoContas] FOREIGN KEY ([IdConta]) REFERENCES [dbo].[PlanoContas] ([IdConta]),
    CONSTRAINT [FK_Web_Receitas_Usuarios] FOREIGN KEY ([IdUsuarioSubSecao]) REFERENCES [dbo].[Usuarios] ([IdUsuario]),
    CONSTRAINT [FK_Web_Receitas_Usuarios1] FOREIGN KEY ([IdUsuarioSIPRO]) REFERENCES [dbo].[Usuarios] ([IdUsuario])
);

