CREATE TABLE [dbo].[Web_DocumentosSISDOC] (
    [IdWeb_DocumentosSISDOC]      INT            IDENTITY (1, 1) NOT NULL,
    [IdDocumento]                 INT            NULL,
    [IdProfissional]              INT            NULL,
    [IdPessoaJuridica]            INT            NULL,
    [IdPessoa]                    INT            NULL,
    [IdModeloDocumento]           INT            NULL,
    [IdTipoDocumento]             INT            NULL,
    [IdSituacaoDocumento]         INT            NULL,
    [IdNivelDocumento]            INT            NOT NULL,
    [IdFuncao]                    INT            NULL,
    [IndOrigemDoc]                CHAR (1)       NOT NULL,
    [Pessoa]                      VARCHAR (120)  NULL,
    [NumeroDocumento]             VARCHAR (50)   NULL,
    [ComplementoRemetente]        VARCHAR (100)  NULL,
    [Assunto]                     TEXT           NULL,
    [Referencia]                  VARCHAR (80)   NULL,
    [DataHoraEmissao]             DATETIME       NULL,
    [DataDocumento]               DATETIME       NULL,
    [DataPrevistaSolucao]         DATETIME       NULL,
    [DataSolucao]                 DATETIME       NULL,
    [NumProtocolo]                INT            NULL,
    [AnoProtocolo]                INT            NULL,
    [CaminhoFisico]               VARCHAR (60)   NULL,
    [Vinculos]                    VARCHAR (120)  NULL,
    [PrazoRespostaDias]           INT            NULL,
    [Observacoes]                 TEXT           NULL,
    [Plenaria]                    BIT            NULL,
    [DataRecebimento]             DATETIME       NULL,
    [IdComplementoRemetente]      INT            NULL,
    [IdUsuarioCriacao]            INT            NULL,
    [IdProcessoOriginou]          INT            NULL,
    [IdProfissionalRequerido]     INT            NULL,
    [IdPessoaRequerido]           INT            NULL,
    [IdPessoaJuridicaRequerido]   INT            NULL,
    [IdDepartamentoCriacao]       INT            NULL,
    [idFormaEntregaDocumento]     INT            NULL,
    [Arquivo]                     IMAGE          NULL,
    [ValorDespesaCustas]          MONEY          NULL,
    [ValorDespesaCopiasPagas]     MONEY          NULL,
    [ValorDespesaCopiasFaturadas] MONEY          NULL,
    [ValorDespesaCorreio]         MONEY          NULL,
    [ValorTaxaServico]            MONEY          NULL,
    [NomeCidade]                  VARCHAR (30)   NULL,
    [SiglaUF]                     CHAR (2)       NULL,
    [CodiAutenticidadeWeb]        VARCHAR (50)   NULL,
    [CodigoAutenticidadeWeb]      VARCHAR (50)   NULL,
    [DadosArquivo]                IMAGE          NULL,
    [IndCriacaoDoc]               BIT            CONSTRAINT [Ind_CriacaoDoc_WEB] DEFAULT ((1)) NOT NULL,
    [IdLote]                      INT            NULL,
    [DataUltAlteracaoAssunto]     DATETIME       NULL,
    [UsuarioAlteracaoAssunto]     VARCHAR (30)   NULL,
    [DeptoAlteracaoAssunto]       VARCHAR (60)   NULL,
    [CorrespondenciaDevolvida]    BIT            NULL,
    [AtualizacaoWeb]              VARCHAR (5000) NULL,
    [IndAtualizacao]              BIT            DEFAULT ((0)) NULL,
    [DataBaixa]                   DATETIME       NULL,
    [DataAtualizacao]             DATETIME       NULL,
    [IdProfissional2]             INT            NULL,
    [IdPessoaJuridica2]           INT            NULL,
    CONSTRAINT [PK_Web_DocumentosSISDOC] PRIMARY KEY CLUSTERED ([IdWeb_DocumentosSISDOC] ASC)
);

