CREATE TABLE [dbo].[Web_ExperienciasProfissionais] (
    [IdWeb_ExperienciaProfissional] INT            IDENTITY (1, 1) NOT NULL,
    [IdExperienciaProfissional]     INT            NOT NULL,
    [IdProfissional]                INT            NULL,
    [IdPessoaJuridica]              INT            NULL,
    [IdPessoa]                      INT            NULL,
    [IdVinculo]                     INT            NULL,
    [IdEntidadeClasse]              INT            NULL,
    [IdAtividade]                   INT            NULL,
    [IdAreaAtuacao]                 INT            NULL,
    [IdSetorAtuacao]                INT            NULL,
    [IdNatureza]                    INT            NULL,
    [IdTipoPessoa]                  INT            NULL,
    [IdCidadeAtuacao]               INT            NULL,
    [Funcao]                        VARCHAR (40)   NULL,
    [CargaHorariaSemanal]           FLOAT (53)     NULL,
    [Remuneracao]                   MONEY          NULL,
    [DataAdmissao]                  DATETIME       NULL,
    [DataDemissao]                  DATETIME       NULL,
    [HorarioTrabalho]               VARCHAR (15)   NULL,
    [ExerceAtividade]               BIT            NULL,
    [Periodo]                       VARCHAR (30)   NULL,
    [E_ResponsavelTecnico]          BIT            NULL,
    [AtualizacaoWeb]                VARCHAR (5000) NULL,
    [IndAtualizacao]                BIT            NULL,
    [DataBaixa]                     DATETIME       NULL,
    [DataAtualizacao]               DATETIME       NULL,
    [idSiscafWeb]                   INT            NULL,
    [IdEntidadeClassePJ]            INT            NULL,
    [UFAreaAtuacao]                 VARCHAR (2)    NULL,
    [AreaAtuacaoDivulgacao]         BIT            CONSTRAINT [DF__Experienc__AreaA__6DEDDB13_WEB] DEFAULT ((0)) NOT NULL,
    [SetorAtuacaoDivulgacao]        BIT            CONSTRAINT [DF__Experienc__Setor__6EE1FF4C_WEB] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Web_ExperienciasProfissionais] PRIMARY KEY CLUSTERED ([IdWeb_ExperienciaProfissional] ASC)
);

