CREATE TABLE [dbo].[WEB_PessoasJuridicas] (
    [IdWeb_PessoaJuridica]          INT            IDENTITY (1, 1) NOT NULL,
    [IdPessoaJuridica]              INT            NOT NULL,
    [IdUnidadeConselho]             INT            NULL,
    [IdSubRegiao]                   INT            NULL,
    [IdNatureza]                    INT            NULL,
    [IdMatriz]                      INT            NULL,
    [IdTipoInscricao]               INT            NULL,
    [SituacaoAtual]                 VARCHAR (50)   NULL,
    [CategoriaAtual]                VARCHAR (40)   NULL,
    [CNPJ]                          VARCHAR (14)   NULL,
    [InscricaoEstadual]             VARCHAR (14)   NULL,
    [Nome]                          VARCHAR (100)  NOT NULL,
    [NomeFantasia]                  VARCHAR (80)   NULL,
    [Codigo]                        VARCHAR (5)    NULL,
    [Sigla]                         VARCHAR (15)   NULL,
    [DataFundacao]                  DATETIME       NULL,
    [EMail]                         VARCHAR (250)  NULL,
    [Telefone]                      VARCHAR (100)  NULL,
    [Endereco]                      VARCHAR (60)   NULL,
    [NomeBairro]                    VARCHAR (35)   NULL,
    [NomeCidade]                    VARCHAR (30)   NULL,
    [SiglaUf]                       VARCHAR (2)    NULL,
    [CEP]                           VARCHAR (8)    NULL,
    [Atualizado]                    BIT            NULL,
    [DataUltimaAtualizacao]         DATETIME       NULL,
    [RegistroConselhoAtual]         VARCHAR (20)   NULL,
    [DataInscricao]                 DATETIME       NULL,
    [Observacoes]                   VARCHAR (8000) NULL,
    [Processo]                      VARCHAR (15)   NULL,
    [CaixaPostal]                   VARCHAR (15)   NULL,
    [IndicativoPJ1]                 BIT            NULL,
    [IndicativoPJ2]                 BIT            NULL,
    [IndicativoPJ3]                 BIT            NULL,
    [AtualizacaoWeb]                VARCHAR (5000) NULL,
    [IndAtualizacao]                BIT            CONSTRAINT [DF__WEB_Pesso__IndAt__17A7B2DC] DEFAULT ((0)) NULL,
    [DataBaixa]                     DATETIME       NULL,
    [DataAtualizacao]               DATETIME       NULL,
    [UsuarioUltimaAtualizacao]      VARCHAR (35)   NULL,
    [DtUltimaAtualizacaoContato]    DATETIME       NULL,
    [UsuUltimaAtualizacaoContato]   VARCHAR (150)  NULL,
    [DepartamentoUltimaAtualizacao] VARCHAR (60)   NULL,
    [IdPesJuridOld]                 INT            NULL,
    [IDEntidadeOld]                 INT            NULL,
    [Atividades]                    VARCHAR (8000) NULL,
    [DataInclusaoEmail]             DATETIME       NULL,
    [TelefoneCelular]               VARCHAR (100)  NULL,
    [TelefoneOutros]                VARCHAR (100)  NULL,
    [CodigoBarras]                  VARCHAR (16)   NULL,
    [IdFaixaCapital]                INT            NULL,
    [Site]                          VARCHAR (50)   NULL,
    [AlfaOutros1PJ]                 VARCHAR (80)   NULL,
    [idTabela1PJ]                   INT            NULL,
    [ExibirDadosWeb]                BIT            NULL,
    [AlfaOutros2PJ]                 VARCHAR (80)   NULL,
    [AlfaOutros3PJ]                 VARCHAR (80)   NULL,
    [IdDetalhePessoa1]              INT            NULL,
    [IdDetalhePessoa2]              INT            NULL,
    [IdDetalhePessoa3]              INT            NULL,
    [IdDetalhePessoa4]              INT            NULL,
    [IdDetalhePessoa5]              INT            NULL,
    [MalaDireta]                    BIT            NULL,
    [AgenciaDebitoConta]            VARCHAR (5)    NULL,
    [ContaDebitoConta]              VARCHAR (15)   NULL,
    [IdBancoDebitoConta]            INT            NULL,
    [NomeUsuario]                   VARCHAR (30)   NULL,
    [DepartamentoUsuario]           VARCHAR (60)   NULL,
    [DepUltimaAtualizacaoContato]   VARCHAR (60)   NULL,
    [Data1PJ]                       DATETIME       NULL,
    [MotivoEnquadramento]           VARCHAR (4000) NULL,
    [IdPaisEndereco]                INT            NULL,
    [ComplementoEndereco]           VARCHAR (8000) NULL,
    [Data2PJ]                       DATETIME       NULL,
    [Data3PJ]                       DATETIME       NULL,
    [Data4PJ]                       DATETIME       NULL,
    [IdRegiaoAdministrativa]        INT            NULL,
    [IdOrigemInscricao]             INT            NULL,
    [IdUsuarioCriacao]              INT            NULL,
    [IdDepartamentoCriacao]         INT            NULL,
    [IdDelegaciaCriacao]            INT            NULL,
    [NIRE]                          VARCHAR (20)   NULL,
    [DtConstitutiva]                DATETIME       NULL,
    [DtAltEndereco]                 DATETIME       NULL,
    [DtAltCapSocial]                DATETIME       NULL,
    [DtAltContratual]               DATETIME       NULL,
    [ProcessoSituacao]              INT            NULL,
    [ProcessoDataAbertura]          DATETIME       NULL,
    [ProcessoDataConclusao]         DATETIME       NULL,
    [NumeroSeguranca]               INT            NULL,
    [E_Filial]                      BIT            CONSTRAINT [DEF_PessoasJuridicas_E_Filial_WEB] DEFAULT ((0)) NOT NULL,
    [DissolucaoContratual]          BIT            CONSTRAINT [DEF_PessoasJuridicas_DissolucaoContratual_WEB] DEFAULT ((0)) NOT NULL,
    [RedesSociais]                  VARCHAR (1000) NULL,
    [DataPedidoInscricao]           DATETIME       NULL,
    [IdSoci]                        INT            NULL,
    [Livro]                         VARCHAR (10)   NULL,
    [Folha]                         VARCHAR (10)   NULL,
    [SiteDivulgacao]                BIT            NULL,
    [EMailDivulgacao]               BIT            NULL,
    [TelefoneDivulgacao]            BIT            NULL,
    [TelCelDivulgacao]              BIT            NULL,
    [TelOutDivulgacao]              BIT            NULL,
    [CalculaPorte]                  BIT            CONSTRAINT [DF_PessoasJuridicas_CalculaPorte_WEB] DEFAULT ((0)) NOT NULL,
    [QtdFunc]                       INT            NULL,
    [Potencia]                      INT            NULL,
    [Porte]                         VARCHAR (20)   CONSTRAINT [DF_PessoasJuridicas_Porte_WEB] DEFAULT ('Médio-Grande Porte') NOT NULL,
    CONSTRAINT [PK_Web_PessoasJuridicas] PRIMARY KEY CLUSTERED ([IdWeb_PessoaJuridica] ASC)
);

